package com.world.education.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class StudentInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student_info
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student_info
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student_info
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbggenerated
     */
    public StudentInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table student_info
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andStudentIdIsNull() {
            addCriterion("student_Id is null");
            return (Criteria) this;
        }

        public Criteria andStudentIdIsNotNull() {
            addCriterion("student_Id is not null");
            return (Criteria) this;
        }

        public Criteria andStudentIdEqualTo(Integer value) {
            addCriterion("student_Id =", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotEqualTo(Integer value) {
            addCriterion("student_Id <>", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdGreaterThan(Integer value) {
            addCriterion("student_Id >", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("student_Id >=", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLessThan(Integer value) {
            addCriterion("student_Id <", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLessThanOrEqualTo(Integer value) {
            addCriterion("student_Id <=", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdIn(List<Integer> values) {
            addCriterion("student_Id in", values, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotIn(List<Integer> values) {
            addCriterion("student_Id not in", values, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdBetween(Integer value1, Integer value2) {
            addCriterion("student_Id between", value1, value2, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotBetween(Integer value1, Integer value2) {
            addCriterion("student_Id not between", value1, value2, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentNameIsNull() {
            addCriterion("student_Name is null");
            return (Criteria) this;
        }

        public Criteria andStudentNameIsNotNull() {
            addCriterion("student_Name is not null");
            return (Criteria) this;
        }

        public Criteria andStudentNameEqualTo(String value) {
            addCriterion("student_Name =", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameNotEqualTo(String value) {
            addCriterion("student_Name <>", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameGreaterThan(String value) {
            addCriterion("student_Name >", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameGreaterThanOrEqualTo(String value) {
            addCriterion("student_Name >=", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameLessThan(String value) {
            addCriterion("student_Name <", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameLessThanOrEqualTo(String value) {
            addCriterion("student_Name <=", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameLike(String value) {
            addCriterion("student_Name like", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameNotLike(String value) {
            addCriterion("student_Name not like", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameIn(List<String> values) {
            addCriterion("student_Name in", values, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameNotIn(List<String> values) {
            addCriterion("student_Name not in", values, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameBetween(String value1, String value2) {
            addCriterion("student_Name between", value1, value2, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameNotBetween(String value1, String value2) {
            addCriterion("student_Name not between", value1, value2, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentGenderIsNull() {
            addCriterion("student_Gender is null");
            return (Criteria) this;
        }

        public Criteria andStudentGenderIsNotNull() {
            addCriterion("student_Gender is not null");
            return (Criteria) this;
        }

        public Criteria andStudentGenderEqualTo(String value) {
            addCriterion("student_Gender =", value, "studentGender");
            return (Criteria) this;
        }

        public Criteria andStudentGenderNotEqualTo(String value) {
            addCriterion("student_Gender <>", value, "studentGender");
            return (Criteria) this;
        }

        public Criteria andStudentGenderGreaterThan(String value) {
            addCriterion("student_Gender >", value, "studentGender");
            return (Criteria) this;
        }

        public Criteria andStudentGenderGreaterThanOrEqualTo(String value) {
            addCriterion("student_Gender >=", value, "studentGender");
            return (Criteria) this;
        }

        public Criteria andStudentGenderLessThan(String value) {
            addCriterion("student_Gender <", value, "studentGender");
            return (Criteria) this;
        }

        public Criteria andStudentGenderLessThanOrEqualTo(String value) {
            addCriterion("student_Gender <=", value, "studentGender");
            return (Criteria) this;
        }

        public Criteria andStudentGenderLike(String value) {
            addCriterion("student_Gender like", value, "studentGender");
            return (Criteria) this;
        }

        public Criteria andStudentGenderNotLike(String value) {
            addCriterion("student_Gender not like", value, "studentGender");
            return (Criteria) this;
        }

        public Criteria andStudentGenderIn(List<String> values) {
            addCriterion("student_Gender in", values, "studentGender");
            return (Criteria) this;
        }

        public Criteria andStudentGenderNotIn(List<String> values) {
            addCriterion("student_Gender not in", values, "studentGender");
            return (Criteria) this;
        }

        public Criteria andStudentGenderBetween(String value1, String value2) {
            addCriterion("student_Gender between", value1, value2, "studentGender");
            return (Criteria) this;
        }

        public Criteria andStudentGenderNotBetween(String value1, String value2) {
            addCriterion("student_Gender not between", value1, value2, "studentGender");
            return (Criteria) this;
        }

        public Criteria andStudentRacialIsNull() {
            addCriterion("student_Racial is null");
            return (Criteria) this;
        }

        public Criteria andStudentRacialIsNotNull() {
            addCriterion("student_Racial is not null");
            return (Criteria) this;
        }

        public Criteria andStudentRacialEqualTo(String value) {
            addCriterion("student_Racial =", value, "studentRacial");
            return (Criteria) this;
        }

        public Criteria andStudentRacialNotEqualTo(String value) {
            addCriterion("student_Racial <>", value, "studentRacial");
            return (Criteria) this;
        }

        public Criteria andStudentRacialGreaterThan(String value) {
            addCriterion("student_Racial >", value, "studentRacial");
            return (Criteria) this;
        }

        public Criteria andStudentRacialGreaterThanOrEqualTo(String value) {
            addCriterion("student_Racial >=", value, "studentRacial");
            return (Criteria) this;
        }

        public Criteria andStudentRacialLessThan(String value) {
            addCriterion("student_Racial <", value, "studentRacial");
            return (Criteria) this;
        }

        public Criteria andStudentRacialLessThanOrEqualTo(String value) {
            addCriterion("student_Racial <=", value, "studentRacial");
            return (Criteria) this;
        }

        public Criteria andStudentRacialLike(String value) {
            addCriterion("student_Racial like", value, "studentRacial");
            return (Criteria) this;
        }

        public Criteria andStudentRacialNotLike(String value) {
            addCriterion("student_Racial not like", value, "studentRacial");
            return (Criteria) this;
        }

        public Criteria andStudentRacialIn(List<String> values) {
            addCriterion("student_Racial in", values, "studentRacial");
            return (Criteria) this;
        }

        public Criteria andStudentRacialNotIn(List<String> values) {
            addCriterion("student_Racial not in", values, "studentRacial");
            return (Criteria) this;
        }

        public Criteria andStudentRacialBetween(String value1, String value2) {
            addCriterion("student_Racial between", value1, value2, "studentRacial");
            return (Criteria) this;
        }

        public Criteria andStudentRacialNotBetween(String value1, String value2) {
            addCriterion("student_Racial not between", value1, value2, "studentRacial");
            return (Criteria) this;
        }

        public Criteria andStudentBirthdayIsNull() {
            addCriterion("student_Birthday is null");
            return (Criteria) this;
        }

        public Criteria andStudentBirthdayIsNotNull() {
            addCriterion("student_Birthday is not null");
            return (Criteria) this;
        }

        public Criteria andStudentBirthdayEqualTo(Date value) {
            addCriterionForJDBCDate("student_Birthday =", value, "studentBirthday");
            return (Criteria) this;
        }

        public Criteria andStudentBirthdayNotEqualTo(Date value) {
            addCriterionForJDBCDate("student_Birthday <>", value, "studentBirthday");
            return (Criteria) this;
        }

        public Criteria andStudentBirthdayGreaterThan(Date value) {
            addCriterionForJDBCDate("student_Birthday >", value, "studentBirthday");
            return (Criteria) this;
        }

        public Criteria andStudentBirthdayGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("student_Birthday >=", value, "studentBirthday");
            return (Criteria) this;
        }

        public Criteria andStudentBirthdayLessThan(Date value) {
            addCriterionForJDBCDate("student_Birthday <", value, "studentBirthday");
            return (Criteria) this;
        }

        public Criteria andStudentBirthdayLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("student_Birthday <=", value, "studentBirthday");
            return (Criteria) this;
        }

        public Criteria andStudentBirthdayIn(List<Date> values) {
            addCriterionForJDBCDate("student_Birthday in", values, "studentBirthday");
            return (Criteria) this;
        }

        public Criteria andStudentBirthdayNotIn(List<Date> values) {
            addCriterionForJDBCDate("student_Birthday not in", values, "studentBirthday");
            return (Criteria) this;
        }

        public Criteria andStudentBirthdayBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("student_Birthday between", value1, value2, "studentBirthday");
            return (Criteria) this;
        }

        public Criteria andStudentBirthdayNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("student_Birthday not between", value1, value2, "studentBirthday");
            return (Criteria) this;
        }

        public Criteria andStudentJoinTimeIsNull() {
            addCriterion("student_Join_Time is null");
            return (Criteria) this;
        }

        public Criteria andStudentJoinTimeIsNotNull() {
            addCriterion("student_Join_Time is not null");
            return (Criteria) this;
        }

        public Criteria andStudentJoinTimeEqualTo(Date value) {
            addCriterionForJDBCDate("student_Join_Time =", value, "studentJoinTime");
            return (Criteria) this;
        }

        public Criteria andStudentJoinTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("student_Join_Time <>", value, "studentJoinTime");
            return (Criteria) this;
        }

        public Criteria andStudentJoinTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("student_Join_Time >", value, "studentJoinTime");
            return (Criteria) this;
        }

        public Criteria andStudentJoinTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("student_Join_Time >=", value, "studentJoinTime");
            return (Criteria) this;
        }

        public Criteria andStudentJoinTimeLessThan(Date value) {
            addCriterionForJDBCDate("student_Join_Time <", value, "studentJoinTime");
            return (Criteria) this;
        }

        public Criteria andStudentJoinTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("student_Join_Time <=", value, "studentJoinTime");
            return (Criteria) this;
        }

        public Criteria andStudentJoinTimeIn(List<Date> values) {
            addCriterionForJDBCDate("student_Join_Time in", values, "studentJoinTime");
            return (Criteria) this;
        }

        public Criteria andStudentJoinTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("student_Join_Time not in", values, "studentJoinTime");
            return (Criteria) this;
        }

        public Criteria andStudentJoinTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("student_Join_Time between", value1, value2, "studentJoinTime");
            return (Criteria) this;
        }

        public Criteria andStudentJoinTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("student_Join_Time not between", value1, value2, "studentJoinTime");
            return (Criteria) this;
        }

        public Criteria andStudentMajorIsNull() {
            addCriterion("student_Major is null");
            return (Criteria) this;
        }

        public Criteria andStudentMajorIsNotNull() {
            addCriterion("student_Major is not null");
            return (Criteria) this;
        }

        public Criteria andStudentMajorEqualTo(String value) {
            addCriterion("student_Major =", value, "studentMajor");
            return (Criteria) this;
        }

        public Criteria andStudentMajorNotEqualTo(String value) {
            addCriterion("student_Major <>", value, "studentMajor");
            return (Criteria) this;
        }

        public Criteria andStudentMajorGreaterThan(String value) {
            addCriterion("student_Major >", value, "studentMajor");
            return (Criteria) this;
        }

        public Criteria andStudentMajorGreaterThanOrEqualTo(String value) {
            addCriterion("student_Major >=", value, "studentMajor");
            return (Criteria) this;
        }

        public Criteria andStudentMajorLessThan(String value) {
            addCriterion("student_Major <", value, "studentMajor");
            return (Criteria) this;
        }

        public Criteria andStudentMajorLessThanOrEqualTo(String value) {
            addCriterion("student_Major <=", value, "studentMajor");
            return (Criteria) this;
        }

        public Criteria andStudentMajorLike(String value) {
            addCriterion("student_Major like", value, "studentMajor");
            return (Criteria) this;
        }

        public Criteria andStudentMajorNotLike(String value) {
            addCriterion("student_Major not like", value, "studentMajor");
            return (Criteria) this;
        }

        public Criteria andStudentMajorIn(List<String> values) {
            addCriterion("student_Major in", values, "studentMajor");
            return (Criteria) this;
        }

        public Criteria andStudentMajorNotIn(List<String> values) {
            addCriterion("student_Major not in", values, "studentMajor");
            return (Criteria) this;
        }

        public Criteria andStudentMajorBetween(String value1, String value2) {
            addCriterion("student_Major between", value1, value2, "studentMajor");
            return (Criteria) this;
        }

        public Criteria andStudentMajorNotBetween(String value1, String value2) {
            addCriterion("student_Major not between", value1, value2, "studentMajor");
            return (Criteria) this;
        }

        public Criteria andStudentClassIsNull() {
            addCriterion("student_Class is null");
            return (Criteria) this;
        }

        public Criteria andStudentClassIsNotNull() {
            addCriterion("student_Class is not null");
            return (Criteria) this;
        }

        public Criteria andStudentClassEqualTo(String value) {
            addCriterion("student_Class =", value, "studentClass");
            return (Criteria) this;
        }

        public Criteria andStudentClassNotEqualTo(String value) {
            addCriterion("student_Class <>", value, "studentClass");
            return (Criteria) this;
        }

        public Criteria andStudentClassGreaterThan(String value) {
            addCriterion("student_Class >", value, "studentClass");
            return (Criteria) this;
        }

        public Criteria andStudentClassGreaterThanOrEqualTo(String value) {
            addCriterion("student_Class >=", value, "studentClass");
            return (Criteria) this;
        }

        public Criteria andStudentClassLessThan(String value) {
            addCriterion("student_Class <", value, "studentClass");
            return (Criteria) this;
        }

        public Criteria andStudentClassLessThanOrEqualTo(String value) {
            addCriterion("student_Class <=", value, "studentClass");
            return (Criteria) this;
        }

        public Criteria andStudentClassLike(String value) {
            addCriterion("student_Class like", value, "studentClass");
            return (Criteria) this;
        }

        public Criteria andStudentClassNotLike(String value) {
            addCriterion("student_Class not like", value, "studentClass");
            return (Criteria) this;
        }

        public Criteria andStudentClassIn(List<String> values) {
            addCriterion("student_Class in", values, "studentClass");
            return (Criteria) this;
        }

        public Criteria andStudentClassNotIn(List<String> values) {
            addCriterion("student_Class not in", values, "studentClass");
            return (Criteria) this;
        }

        public Criteria andStudentClassBetween(String value1, String value2) {
            addCriterion("student_Class between", value1, value2, "studentClass");
            return (Criteria) this;
        }

        public Criteria andStudentClassNotBetween(String value1, String value2) {
            addCriterion("student_Class not between", value1, value2, "studentClass");
            return (Criteria) this;
        }

        public Criteria andStudentFirstParentIsNull() {
            addCriterion("student_First_Parent is null");
            return (Criteria) this;
        }

        public Criteria andStudentFirstParentIsNotNull() {
            addCriterion("student_First_Parent is not null");
            return (Criteria) this;
        }

        public Criteria andStudentFirstParentEqualTo(String value) {
            addCriterion("student_First_Parent =", value, "studentFirstParent");
            return (Criteria) this;
        }

        public Criteria andStudentFirstParentNotEqualTo(String value) {
            addCriterion("student_First_Parent <>", value, "studentFirstParent");
            return (Criteria) this;
        }

        public Criteria andStudentFirstParentGreaterThan(String value) {
            addCriterion("student_First_Parent >", value, "studentFirstParent");
            return (Criteria) this;
        }

        public Criteria andStudentFirstParentGreaterThanOrEqualTo(String value) {
            addCriterion("student_First_Parent >=", value, "studentFirstParent");
            return (Criteria) this;
        }

        public Criteria andStudentFirstParentLessThan(String value) {
            addCriterion("student_First_Parent <", value, "studentFirstParent");
            return (Criteria) this;
        }

        public Criteria andStudentFirstParentLessThanOrEqualTo(String value) {
            addCriterion("student_First_Parent <=", value, "studentFirstParent");
            return (Criteria) this;
        }

        public Criteria andStudentFirstParentLike(String value) {
            addCriterion("student_First_Parent like", value, "studentFirstParent");
            return (Criteria) this;
        }

        public Criteria andStudentFirstParentNotLike(String value) {
            addCriterion("student_First_Parent not like", value, "studentFirstParent");
            return (Criteria) this;
        }

        public Criteria andStudentFirstParentIn(List<String> values) {
            addCriterion("student_First_Parent in", values, "studentFirstParent");
            return (Criteria) this;
        }

        public Criteria andStudentFirstParentNotIn(List<String> values) {
            addCriterion("student_First_Parent not in", values, "studentFirstParent");
            return (Criteria) this;
        }

        public Criteria andStudentFirstParentBetween(String value1, String value2) {
            addCriterion("student_First_Parent between", value1, value2, "studentFirstParent");
            return (Criteria) this;
        }

        public Criteria andStudentFirstParentNotBetween(String value1, String value2) {
            addCriterion("student_First_Parent not between", value1, value2, "studentFirstParent");
            return (Criteria) this;
        }

        public Criteria andStudentFirstParentWorkIsNull() {
            addCriterion("student_First_Parent_Work is null");
            return (Criteria) this;
        }

        public Criteria andStudentFirstParentWorkIsNotNull() {
            addCriterion("student_First_Parent_Work is not null");
            return (Criteria) this;
        }

        public Criteria andStudentFirstParentWorkEqualTo(String value) {
            addCriterion("student_First_Parent_Work =", value, "studentFirstParentWork");
            return (Criteria) this;
        }

        public Criteria andStudentFirstParentWorkNotEqualTo(String value) {
            addCriterion("student_First_Parent_Work <>", value, "studentFirstParentWork");
            return (Criteria) this;
        }

        public Criteria andStudentFirstParentWorkGreaterThan(String value) {
            addCriterion("student_First_Parent_Work >", value, "studentFirstParentWork");
            return (Criteria) this;
        }

        public Criteria andStudentFirstParentWorkGreaterThanOrEqualTo(String value) {
            addCriterion("student_First_Parent_Work >=", value, "studentFirstParentWork");
            return (Criteria) this;
        }

        public Criteria andStudentFirstParentWorkLessThan(String value) {
            addCriterion("student_First_Parent_Work <", value, "studentFirstParentWork");
            return (Criteria) this;
        }

        public Criteria andStudentFirstParentWorkLessThanOrEqualTo(String value) {
            addCriterion("student_First_Parent_Work <=", value, "studentFirstParentWork");
            return (Criteria) this;
        }

        public Criteria andStudentFirstParentWorkLike(String value) {
            addCriterion("student_First_Parent_Work like", value, "studentFirstParentWork");
            return (Criteria) this;
        }

        public Criteria andStudentFirstParentWorkNotLike(String value) {
            addCriterion("student_First_Parent_Work not like", value, "studentFirstParentWork");
            return (Criteria) this;
        }

        public Criteria andStudentFirstParentWorkIn(List<String> values) {
            addCriterion("student_First_Parent_Work in", values, "studentFirstParentWork");
            return (Criteria) this;
        }

        public Criteria andStudentFirstParentWorkNotIn(List<String> values) {
            addCriterion("student_First_Parent_Work not in", values, "studentFirstParentWork");
            return (Criteria) this;
        }

        public Criteria andStudentFirstParentWorkBetween(String value1, String value2) {
            addCriterion("student_First_Parent_Work between", value1, value2, "studentFirstParentWork");
            return (Criteria) this;
        }

        public Criteria andStudentFirstParentWorkNotBetween(String value1, String value2) {
            addCriterion("student_First_Parent_Work not between", value1, value2, "studentFirstParentWork");
            return (Criteria) this;
        }

        public Criteria andStudentSecondParentIsNull() {
            addCriterion("student_Second_Parent is null");
            return (Criteria) this;
        }

        public Criteria andStudentSecondParentIsNotNull() {
            addCriterion("student_Second_Parent is not null");
            return (Criteria) this;
        }

        public Criteria andStudentSecondParentEqualTo(String value) {
            addCriterion("student_Second_Parent =", value, "studentSecondParent");
            return (Criteria) this;
        }

        public Criteria andStudentSecondParentNotEqualTo(String value) {
            addCriterion("student_Second_Parent <>", value, "studentSecondParent");
            return (Criteria) this;
        }

        public Criteria andStudentSecondParentGreaterThan(String value) {
            addCriterion("student_Second_Parent >", value, "studentSecondParent");
            return (Criteria) this;
        }

        public Criteria andStudentSecondParentGreaterThanOrEqualTo(String value) {
            addCriterion("student_Second_Parent >=", value, "studentSecondParent");
            return (Criteria) this;
        }

        public Criteria andStudentSecondParentLessThan(String value) {
            addCriterion("student_Second_Parent <", value, "studentSecondParent");
            return (Criteria) this;
        }

        public Criteria andStudentSecondParentLessThanOrEqualTo(String value) {
            addCriterion("student_Second_Parent <=", value, "studentSecondParent");
            return (Criteria) this;
        }

        public Criteria andStudentSecondParentLike(String value) {
            addCriterion("student_Second_Parent like", value, "studentSecondParent");
            return (Criteria) this;
        }

        public Criteria andStudentSecondParentNotLike(String value) {
            addCriterion("student_Second_Parent not like", value, "studentSecondParent");
            return (Criteria) this;
        }

        public Criteria andStudentSecondParentIn(List<String> values) {
            addCriterion("student_Second_Parent in", values, "studentSecondParent");
            return (Criteria) this;
        }

        public Criteria andStudentSecondParentNotIn(List<String> values) {
            addCriterion("student_Second_Parent not in", values, "studentSecondParent");
            return (Criteria) this;
        }

        public Criteria andStudentSecondParentBetween(String value1, String value2) {
            addCriterion("student_Second_Parent between", value1, value2, "studentSecondParent");
            return (Criteria) this;
        }

        public Criteria andStudentSecondParentNotBetween(String value1, String value2) {
            addCriterion("student_Second_Parent not between", value1, value2, "studentSecondParent");
            return (Criteria) this;
        }

        public Criteria andStudentsecondParentWorkIsNull() {
            addCriterion("studentSecond_Parent_Work is null");
            return (Criteria) this;
        }

        public Criteria andStudentsecondParentWorkIsNotNull() {
            addCriterion("studentSecond_Parent_Work is not null");
            return (Criteria) this;
        }

        public Criteria andStudentsecondParentWorkEqualTo(String value) {
            addCriterion("studentSecond_Parent_Work =", value, "studentsecondParentWork");
            return (Criteria) this;
        }

        public Criteria andStudentsecondParentWorkNotEqualTo(String value) {
            addCriterion("studentSecond_Parent_Work <>", value, "studentsecondParentWork");
            return (Criteria) this;
        }

        public Criteria andStudentsecondParentWorkGreaterThan(String value) {
            addCriterion("studentSecond_Parent_Work >", value, "studentsecondParentWork");
            return (Criteria) this;
        }

        public Criteria andStudentsecondParentWorkGreaterThanOrEqualTo(String value) {
            addCriterion("studentSecond_Parent_Work >=", value, "studentsecondParentWork");
            return (Criteria) this;
        }

        public Criteria andStudentsecondParentWorkLessThan(String value) {
            addCriterion("studentSecond_Parent_Work <", value, "studentsecondParentWork");
            return (Criteria) this;
        }

        public Criteria andStudentsecondParentWorkLessThanOrEqualTo(String value) {
            addCriterion("studentSecond_Parent_Work <=", value, "studentsecondParentWork");
            return (Criteria) this;
        }

        public Criteria andStudentsecondParentWorkLike(String value) {
            addCriterion("studentSecond_Parent_Work like", value, "studentsecondParentWork");
            return (Criteria) this;
        }

        public Criteria andStudentsecondParentWorkNotLike(String value) {
            addCriterion("studentSecond_Parent_Work not like", value, "studentsecondParentWork");
            return (Criteria) this;
        }

        public Criteria andStudentsecondParentWorkIn(List<String> values) {
            addCriterion("studentSecond_Parent_Work in", values, "studentsecondParentWork");
            return (Criteria) this;
        }

        public Criteria andStudentsecondParentWorkNotIn(List<String> values) {
            addCriterion("studentSecond_Parent_Work not in", values, "studentsecondParentWork");
            return (Criteria) this;
        }

        public Criteria andStudentsecondParentWorkBetween(String value1, String value2) {
            addCriterion("studentSecond_Parent_Work between", value1, value2, "studentsecondParentWork");
            return (Criteria) this;
        }

        public Criteria andStudentsecondParentWorkNotBetween(String value1, String value2) {
            addCriterion("studentSecond_Parent_Work not between", value1, value2, "studentsecondParentWork");
            return (Criteria) this;
        }

        public Criteria andStudentNativePlaceIsNull() {
            addCriterion("student_Native_Place is null");
            return (Criteria) this;
        }

        public Criteria andStudentNativePlaceIsNotNull() {
            addCriterion("student_Native_Place is not null");
            return (Criteria) this;
        }

        public Criteria andStudentNativePlaceEqualTo(String value) {
            addCriterion("student_Native_Place =", value, "studentNativePlace");
            return (Criteria) this;
        }

        public Criteria andStudentNativePlaceNotEqualTo(String value) {
            addCriterion("student_Native_Place <>", value, "studentNativePlace");
            return (Criteria) this;
        }

        public Criteria andStudentNativePlaceGreaterThan(String value) {
            addCriterion("student_Native_Place >", value, "studentNativePlace");
            return (Criteria) this;
        }

        public Criteria andStudentNativePlaceGreaterThanOrEqualTo(String value) {
            addCriterion("student_Native_Place >=", value, "studentNativePlace");
            return (Criteria) this;
        }

        public Criteria andStudentNativePlaceLessThan(String value) {
            addCriterion("student_Native_Place <", value, "studentNativePlace");
            return (Criteria) this;
        }

        public Criteria andStudentNativePlaceLessThanOrEqualTo(String value) {
            addCriterion("student_Native_Place <=", value, "studentNativePlace");
            return (Criteria) this;
        }

        public Criteria andStudentNativePlaceLike(String value) {
            addCriterion("student_Native_Place like", value, "studentNativePlace");
            return (Criteria) this;
        }

        public Criteria andStudentNativePlaceNotLike(String value) {
            addCriterion("student_Native_Place not like", value, "studentNativePlace");
            return (Criteria) this;
        }

        public Criteria andStudentNativePlaceIn(List<String> values) {
            addCriterion("student_Native_Place in", values, "studentNativePlace");
            return (Criteria) this;
        }

        public Criteria andStudentNativePlaceNotIn(List<String> values) {
            addCriterion("student_Native_Place not in", values, "studentNativePlace");
            return (Criteria) this;
        }

        public Criteria andStudentNativePlaceBetween(String value1, String value2) {
            addCriterion("student_Native_Place between", value1, value2, "studentNativePlace");
            return (Criteria) this;
        }

        public Criteria andStudentNativePlaceNotBetween(String value1, String value2) {
            addCriterion("student_Native_Place not between", value1, value2, "studentNativePlace");
            return (Criteria) this;
        }

        public Criteria andStudentAddressIsNull() {
            addCriterion("student_Address is null");
            return (Criteria) this;
        }

        public Criteria andStudentAddressIsNotNull() {
            addCriterion("student_Address is not null");
            return (Criteria) this;
        }

        public Criteria andStudentAddressEqualTo(String value) {
            addCriterion("student_Address =", value, "studentAddress");
            return (Criteria) this;
        }

        public Criteria andStudentAddressNotEqualTo(String value) {
            addCriterion("student_Address <>", value, "studentAddress");
            return (Criteria) this;
        }

        public Criteria andStudentAddressGreaterThan(String value) {
            addCriterion("student_Address >", value, "studentAddress");
            return (Criteria) this;
        }

        public Criteria andStudentAddressGreaterThanOrEqualTo(String value) {
            addCriterion("student_Address >=", value, "studentAddress");
            return (Criteria) this;
        }

        public Criteria andStudentAddressLessThan(String value) {
            addCriterion("student_Address <", value, "studentAddress");
            return (Criteria) this;
        }

        public Criteria andStudentAddressLessThanOrEqualTo(String value) {
            addCriterion("student_Address <=", value, "studentAddress");
            return (Criteria) this;
        }

        public Criteria andStudentAddressLike(String value) {
            addCriterion("student_Address like", value, "studentAddress");
            return (Criteria) this;
        }

        public Criteria andStudentAddressNotLike(String value) {
            addCriterion("student_Address not like", value, "studentAddress");
            return (Criteria) this;
        }

        public Criteria andStudentAddressIn(List<String> values) {
            addCriterion("student_Address in", values, "studentAddress");
            return (Criteria) this;
        }

        public Criteria andStudentAddressNotIn(List<String> values) {
            addCriterion("student_Address not in", values, "studentAddress");
            return (Criteria) this;
        }

        public Criteria andStudentAddressBetween(String value1, String value2) {
            addCriterion("student_Address between", value1, value2, "studentAddress");
            return (Criteria) this;
        }

        public Criteria andStudentAddressNotBetween(String value1, String value2) {
            addCriterion("student_Address not between", value1, value2, "studentAddress");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneIsNull() {
            addCriterion("student_Phone is null");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneIsNotNull() {
            addCriterion("student_Phone is not null");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneEqualTo(Integer value) {
            addCriterion("student_Phone =", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneNotEqualTo(Integer value) {
            addCriterion("student_Phone <>", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneGreaterThan(Integer value) {
            addCriterion("student_Phone >", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneGreaterThanOrEqualTo(Integer value) {
            addCriterion("student_Phone >=", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneLessThan(Integer value) {
            addCriterion("student_Phone <", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneLessThanOrEqualTo(Integer value) {
            addCriterion("student_Phone <=", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneIn(List<Integer> values) {
            addCriterion("student_Phone in", values, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneNotIn(List<Integer> values) {
            addCriterion("student_Phone not in", values, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneBetween(Integer value1, Integer value2) {
            addCriterion("student_Phone between", value1, value2, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneNotBetween(Integer value1, Integer value2) {
            addCriterion("student_Phone not between", value1, value2, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentCellPhoneIsNull() {
            addCriterion("student_Cell_Phone is null");
            return (Criteria) this;
        }

        public Criteria andStudentCellPhoneIsNotNull() {
            addCriterion("student_Cell_Phone is not null");
            return (Criteria) this;
        }

        public Criteria andStudentCellPhoneEqualTo(Integer value) {
            addCriterion("student_Cell_Phone =", value, "studentCellPhone");
            return (Criteria) this;
        }

        public Criteria andStudentCellPhoneNotEqualTo(Integer value) {
            addCriterion("student_Cell_Phone <>", value, "studentCellPhone");
            return (Criteria) this;
        }

        public Criteria andStudentCellPhoneGreaterThan(Integer value) {
            addCriterion("student_Cell_Phone >", value, "studentCellPhone");
            return (Criteria) this;
        }

        public Criteria andStudentCellPhoneGreaterThanOrEqualTo(Integer value) {
            addCriterion("student_Cell_Phone >=", value, "studentCellPhone");
            return (Criteria) this;
        }

        public Criteria andStudentCellPhoneLessThan(Integer value) {
            addCriterion("student_Cell_Phone <", value, "studentCellPhone");
            return (Criteria) this;
        }

        public Criteria andStudentCellPhoneLessThanOrEqualTo(Integer value) {
            addCriterion("student_Cell_Phone <=", value, "studentCellPhone");
            return (Criteria) this;
        }

        public Criteria andStudentCellPhoneIn(List<Integer> values) {
            addCriterion("student_Cell_Phone in", values, "studentCellPhone");
            return (Criteria) this;
        }

        public Criteria andStudentCellPhoneNotIn(List<Integer> values) {
            addCriterion("student_Cell_Phone not in", values, "studentCellPhone");
            return (Criteria) this;
        }

        public Criteria andStudentCellPhoneBetween(Integer value1, Integer value2) {
            addCriterion("student_Cell_Phone between", value1, value2, "studentCellPhone");
            return (Criteria) this;
        }

        public Criteria andStudentCellPhoneNotBetween(Integer value1, Integer value2) {
            addCriterion("student_Cell_Phone not between", value1, value2, "studentCellPhone");
            return (Criteria) this;
        }

        public Criteria andStudentEmailIsNull() {
            addCriterion("student_Email is null");
            return (Criteria) this;
        }

        public Criteria andStudentEmailIsNotNull() {
            addCriterion("student_Email is not null");
            return (Criteria) this;
        }

        public Criteria andStudentEmailEqualTo(String value) {
            addCriterion("student_Email =", value, "studentEmail");
            return (Criteria) this;
        }

        public Criteria andStudentEmailNotEqualTo(String value) {
            addCriterion("student_Email <>", value, "studentEmail");
            return (Criteria) this;
        }

        public Criteria andStudentEmailGreaterThan(String value) {
            addCriterion("student_Email >", value, "studentEmail");
            return (Criteria) this;
        }

        public Criteria andStudentEmailGreaterThanOrEqualTo(String value) {
            addCriterion("student_Email >=", value, "studentEmail");
            return (Criteria) this;
        }

        public Criteria andStudentEmailLessThan(String value) {
            addCriterion("student_Email <", value, "studentEmail");
            return (Criteria) this;
        }

        public Criteria andStudentEmailLessThanOrEqualTo(String value) {
            addCriterion("student_Email <=", value, "studentEmail");
            return (Criteria) this;
        }

        public Criteria andStudentEmailLike(String value) {
            addCriterion("student_Email like", value, "studentEmail");
            return (Criteria) this;
        }

        public Criteria andStudentEmailNotLike(String value) {
            addCriterion("student_Email not like", value, "studentEmail");
            return (Criteria) this;
        }

        public Criteria andStudentEmailIn(List<String> values) {
            addCriterion("student_Email in", values, "studentEmail");
            return (Criteria) this;
        }

        public Criteria andStudentEmailNotIn(List<String> values) {
            addCriterion("student_Email not in", values, "studentEmail");
            return (Criteria) this;
        }

        public Criteria andStudentEmailBetween(String value1, String value2) {
            addCriterion("student_Email between", value1, value2, "studentEmail");
            return (Criteria) this;
        }

        public Criteria andStudentEmailNotBetween(String value1, String value2) {
            addCriterion("student_Email not between", value1, value2, "studentEmail");
            return (Criteria) this;
        }

        public Criteria andStudentPhotoIsNull() {
            addCriterion("student_Photo is null");
            return (Criteria) this;
        }

        public Criteria andStudentPhotoIsNotNull() {
            addCriterion("student_Photo is not null");
            return (Criteria) this;
        }

        public Criteria andStudentPhotoEqualTo(String value) {
            addCriterion("student_Photo =", value, "studentPhoto");
            return (Criteria) this;
        }

        public Criteria andStudentPhotoNotEqualTo(String value) {
            addCriterion("student_Photo <>", value, "studentPhoto");
            return (Criteria) this;
        }

        public Criteria andStudentPhotoGreaterThan(String value) {
            addCriterion("student_Photo >", value, "studentPhoto");
            return (Criteria) this;
        }

        public Criteria andStudentPhotoGreaterThanOrEqualTo(String value) {
            addCriterion("student_Photo >=", value, "studentPhoto");
            return (Criteria) this;
        }

        public Criteria andStudentPhotoLessThan(String value) {
            addCriterion("student_Photo <", value, "studentPhoto");
            return (Criteria) this;
        }

        public Criteria andStudentPhotoLessThanOrEqualTo(String value) {
            addCriterion("student_Photo <=", value, "studentPhoto");
            return (Criteria) this;
        }

        public Criteria andStudentPhotoLike(String value) {
            addCriterion("student_Photo like", value, "studentPhoto");
            return (Criteria) this;
        }

        public Criteria andStudentPhotoNotLike(String value) {
            addCriterion("student_Photo not like", value, "studentPhoto");
            return (Criteria) this;
        }

        public Criteria andStudentPhotoIn(List<String> values) {
            addCriterion("student_Photo in", values, "studentPhoto");
            return (Criteria) this;
        }

        public Criteria andStudentPhotoNotIn(List<String> values) {
            addCriterion("student_Photo not in", values, "studentPhoto");
            return (Criteria) this;
        }

        public Criteria andStudentPhotoBetween(String value1, String value2) {
            addCriterion("student_Photo between", value1, value2, "studentPhoto");
            return (Criteria) this;
        }

        public Criteria andStudentPhotoNotBetween(String value1, String value2) {
            addCriterion("student_Photo not between", value1, value2, "studentPhoto");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table student_info
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table student_info
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}