package com.world.education.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class StudentAffairsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student_affairs
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student_affairs
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student_affairs
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_affairs
     *
     * @mbggenerated
     */
    public StudentAffairsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_affairs
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_affairs
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_affairs
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_affairs
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_affairs
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_affairs
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_affairs
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_affairs
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_affairs
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_affairs
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table student_affairs
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAffairsIdIsNull() {
            addCriterion("affairs_id is null");
            return (Criteria) this;
        }

        public Criteria andAffairsIdIsNotNull() {
            addCriterion("affairs_id is not null");
            return (Criteria) this;
        }

        public Criteria andAffairsIdEqualTo(String value) {
            addCriterion("affairs_id =", value, "affairsId");
            return (Criteria) this;
        }

        public Criteria andAffairsIdNotEqualTo(String value) {
            addCriterion("affairs_id <>", value, "affairsId");
            return (Criteria) this;
        }

        public Criteria andAffairsIdGreaterThan(String value) {
            addCriterion("affairs_id >", value, "affairsId");
            return (Criteria) this;
        }

        public Criteria andAffairsIdGreaterThanOrEqualTo(String value) {
            addCriterion("affairs_id >=", value, "affairsId");
            return (Criteria) this;
        }

        public Criteria andAffairsIdLessThan(String value) {
            addCriterion("affairs_id <", value, "affairsId");
            return (Criteria) this;
        }

        public Criteria andAffairsIdLessThanOrEqualTo(String value) {
            addCriterion("affairs_id <=", value, "affairsId");
            return (Criteria) this;
        }

        public Criteria andAffairsIdLike(String value) {
            addCriterion("affairs_id like", value, "affairsId");
            return (Criteria) this;
        }

        public Criteria andAffairsIdNotLike(String value) {
            addCriterion("affairs_id not like", value, "affairsId");
            return (Criteria) this;
        }

        public Criteria andAffairsIdIn(List<String> values) {
            addCriterion("affairs_id in", values, "affairsId");
            return (Criteria) this;
        }

        public Criteria andAffairsIdNotIn(List<String> values) {
            addCriterion("affairs_id not in", values, "affairsId");
            return (Criteria) this;
        }

        public Criteria andAffairsIdBetween(String value1, String value2) {
            addCriterion("affairs_id between", value1, value2, "affairsId");
            return (Criteria) this;
        }

        public Criteria andAffairsIdNotBetween(String value1, String value2) {
            addCriterion("affairs_id not between", value1, value2, "affairsId");
            return (Criteria) this;
        }

        public Criteria andStudentIdIsNull() {
            addCriterion("student_id is null");
            return (Criteria) this;
        }

        public Criteria andStudentIdIsNotNull() {
            addCriterion("student_id is not null");
            return (Criteria) this;
        }

        public Criteria andStudentIdEqualTo(Integer value) {
            addCriterion("student_id =", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotEqualTo(Integer value) {
            addCriterion("student_id <>", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdGreaterThan(Integer value) {
            addCriterion("student_id >", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("student_id >=", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLessThan(Integer value) {
            addCriterion("student_id <", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLessThanOrEqualTo(Integer value) {
            addCriterion("student_id <=", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdIn(List<Integer> values) {
            addCriterion("student_id in", values, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotIn(List<Integer> values) {
            addCriterion("student_id not in", values, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdBetween(Integer value1, Integer value2) {
            addCriterion("student_id between", value1, value2, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotBetween(Integer value1, Integer value2) {
            addCriterion("student_id not between", value1, value2, "studentId");
            return (Criteria) this;
        }

        public Criteria andApplicationNameIsNull() {
            addCriterion("application_name is null");
            return (Criteria) this;
        }

        public Criteria andApplicationNameIsNotNull() {
            addCriterion("application_name is not null");
            return (Criteria) this;
        }

        public Criteria andApplicationNameEqualTo(String value) {
            addCriterion("application_name =", value, "applicationName");
            return (Criteria) this;
        }

        public Criteria andApplicationNameNotEqualTo(String value) {
            addCriterion("application_name <>", value, "applicationName");
            return (Criteria) this;
        }

        public Criteria andApplicationNameGreaterThan(String value) {
            addCriterion("application_name >", value, "applicationName");
            return (Criteria) this;
        }

        public Criteria andApplicationNameGreaterThanOrEqualTo(String value) {
            addCriterion("application_name >=", value, "applicationName");
            return (Criteria) this;
        }

        public Criteria andApplicationNameLessThan(String value) {
            addCriterion("application_name <", value, "applicationName");
            return (Criteria) this;
        }

        public Criteria andApplicationNameLessThanOrEqualTo(String value) {
            addCriterion("application_name <=", value, "applicationName");
            return (Criteria) this;
        }

        public Criteria andApplicationNameLike(String value) {
            addCriterion("application_name like", value, "applicationName");
            return (Criteria) this;
        }

        public Criteria andApplicationNameNotLike(String value) {
            addCriterion("application_name not like", value, "applicationName");
            return (Criteria) this;
        }

        public Criteria andApplicationNameIn(List<String> values) {
            addCriterion("application_name in", values, "applicationName");
            return (Criteria) this;
        }

        public Criteria andApplicationNameNotIn(List<String> values) {
            addCriterion("application_name not in", values, "applicationName");
            return (Criteria) this;
        }

        public Criteria andApplicationNameBetween(String value1, String value2) {
            addCriterion("application_name between", value1, value2, "applicationName");
            return (Criteria) this;
        }

        public Criteria andApplicationNameNotBetween(String value1, String value2) {
            addCriterion("application_name not between", value1, value2, "applicationName");
            return (Criteria) this;
        }

        public Criteria andApplicationTimeIsNull() {
            addCriterion("application_time is null");
            return (Criteria) this;
        }

        public Criteria andApplicationTimeIsNotNull() {
            addCriterion("application_time is not null");
            return (Criteria) this;
        }

        public Criteria andApplicationTimeEqualTo(Date value) {
            addCriterion("application_time =", value, "applicationTime");
            return (Criteria) this;
        }

        public Criteria andApplicationTimeNotEqualTo(Date value) {
            addCriterion("application_time <>", value, "applicationTime");
            return (Criteria) this;
        }

        public Criteria andApplicationTimeGreaterThan(Date value) {
            addCriterion("application_time >", value, "applicationTime");
            return (Criteria) this;
        }

        public Criteria andApplicationTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("application_time >=", value, "applicationTime");
            return (Criteria) this;
        }

        public Criteria andApplicationTimeLessThan(Date value) {
            addCriterion("application_time <", value, "applicationTime");
            return (Criteria) this;
        }

        public Criteria andApplicationTimeLessThanOrEqualTo(Date value) {
            addCriterion("application_time <=", value, "applicationTime");
            return (Criteria) this;
        }

        public Criteria andApplicationTimeIn(List<Date> values) {
            addCriterion("application_time in", values, "applicationTime");
            return (Criteria) this;
        }

        public Criteria andApplicationTimeNotIn(List<Date> values) {
            addCriterion("application_time not in", values, "applicationTime");
            return (Criteria) this;
        }

        public Criteria andApplicationTimeBetween(Date value1, Date value2) {
            addCriterion("application_time between", value1, value2, "applicationTime");
            return (Criteria) this;
        }

        public Criteria andApplicationTimeNotBetween(Date value1, Date value2) {
            addCriterion("application_time not between", value1, value2, "applicationTime");
            return (Criteria) this;
        }

        public Criteria andAffairsTitleIsNull() {
            addCriterion("affairs_title is null");
            return (Criteria) this;
        }

        public Criteria andAffairsTitleIsNotNull() {
            addCriterion("affairs_title is not null");
            return (Criteria) this;
        }

        public Criteria andAffairsTitleEqualTo(String value) {
            addCriterion("affairs_title =", value, "affairsTitle");
            return (Criteria) this;
        }

        public Criteria andAffairsTitleNotEqualTo(String value) {
            addCriterion("affairs_title <>", value, "affairsTitle");
            return (Criteria) this;
        }

        public Criteria andAffairsTitleGreaterThan(String value) {
            addCriterion("affairs_title >", value, "affairsTitle");
            return (Criteria) this;
        }

        public Criteria andAffairsTitleGreaterThanOrEqualTo(String value) {
            addCriterion("affairs_title >=", value, "affairsTitle");
            return (Criteria) this;
        }

        public Criteria andAffairsTitleLessThan(String value) {
            addCriterion("affairs_title <", value, "affairsTitle");
            return (Criteria) this;
        }

        public Criteria andAffairsTitleLessThanOrEqualTo(String value) {
            addCriterion("affairs_title <=", value, "affairsTitle");
            return (Criteria) this;
        }

        public Criteria andAffairsTitleLike(String value) {
            addCriterion("affairs_title like", value, "affairsTitle");
            return (Criteria) this;
        }

        public Criteria andAffairsTitleNotLike(String value) {
            addCriterion("affairs_title not like", value, "affairsTitle");
            return (Criteria) this;
        }

        public Criteria andAffairsTitleIn(List<String> values) {
            addCriterion("affairs_title in", values, "affairsTitle");
            return (Criteria) this;
        }

        public Criteria andAffairsTitleNotIn(List<String> values) {
            addCriterion("affairs_title not in", values, "affairsTitle");
            return (Criteria) this;
        }

        public Criteria andAffairsTitleBetween(String value1, String value2) {
            addCriterion("affairs_title between", value1, value2, "affairsTitle");
            return (Criteria) this;
        }

        public Criteria andAffairsTitleNotBetween(String value1, String value2) {
            addCriterion("affairs_title not between", value1, value2, "affairsTitle");
            return (Criteria) this;
        }

        public Criteria andApplicationStatusIsNull() {
            addCriterion("application_status is null");
            return (Criteria) this;
        }

        public Criteria andApplicationStatusIsNotNull() {
            addCriterion("application_status is not null");
            return (Criteria) this;
        }

        public Criteria andApplicationStatusEqualTo(String value) {
            addCriterion("application_status =", value, "applicationStatus");
            return (Criteria) this;
        }

        public Criteria andApplicationStatusNotEqualTo(String value) {
            addCriterion("application_status <>", value, "applicationStatus");
            return (Criteria) this;
        }

        public Criteria andApplicationStatusGreaterThan(String value) {
            addCriterion("application_status >", value, "applicationStatus");
            return (Criteria) this;
        }

        public Criteria andApplicationStatusGreaterThanOrEqualTo(String value) {
            addCriterion("application_status >=", value, "applicationStatus");
            return (Criteria) this;
        }

        public Criteria andApplicationStatusLessThan(String value) {
            addCriterion("application_status <", value, "applicationStatus");
            return (Criteria) this;
        }

        public Criteria andApplicationStatusLessThanOrEqualTo(String value) {
            addCriterion("application_status <=", value, "applicationStatus");
            return (Criteria) this;
        }

        public Criteria andApplicationStatusLike(String value) {
            addCriterion("application_status like", value, "applicationStatus");
            return (Criteria) this;
        }

        public Criteria andApplicationStatusNotLike(String value) {
            addCriterion("application_status not like", value, "applicationStatus");
            return (Criteria) this;
        }

        public Criteria andApplicationStatusIn(List<String> values) {
            addCriterion("application_status in", values, "applicationStatus");
            return (Criteria) this;
        }

        public Criteria andApplicationStatusNotIn(List<String> values) {
            addCriterion("application_status not in", values, "applicationStatus");
            return (Criteria) this;
        }

        public Criteria andApplicationStatusBetween(String value1, String value2) {
            addCriterion("application_status between", value1, value2, "applicationStatus");
            return (Criteria) this;
        }

        public Criteria andApplicationStatusNotBetween(String value1, String value2) {
            addCriterion("application_status not between", value1, value2, "applicationStatus");
            return (Criteria) this;
        }

        public Criteria andTheHandlerIsNull() {
            addCriterion("the_handler is null");
            return (Criteria) this;
        }

        public Criteria andTheHandlerIsNotNull() {
            addCriterion("the_handler is not null");
            return (Criteria) this;
        }

        public Criteria andTheHandlerEqualTo(String value) {
            addCriterion("the_handler =", value, "theHandler");
            return (Criteria) this;
        }

        public Criteria andTheHandlerNotEqualTo(String value) {
            addCriterion("the_handler <>", value, "theHandler");
            return (Criteria) this;
        }

        public Criteria andTheHandlerGreaterThan(String value) {
            addCriterion("the_handler >", value, "theHandler");
            return (Criteria) this;
        }

        public Criteria andTheHandlerGreaterThanOrEqualTo(String value) {
            addCriterion("the_handler >=", value, "theHandler");
            return (Criteria) this;
        }

        public Criteria andTheHandlerLessThan(String value) {
            addCriterion("the_handler <", value, "theHandler");
            return (Criteria) this;
        }

        public Criteria andTheHandlerLessThanOrEqualTo(String value) {
            addCriterion("the_handler <=", value, "theHandler");
            return (Criteria) this;
        }

        public Criteria andTheHandlerLike(String value) {
            addCriterion("the_handler like", value, "theHandler");
            return (Criteria) this;
        }

        public Criteria andTheHandlerNotLike(String value) {
            addCriterion("the_handler not like", value, "theHandler");
            return (Criteria) this;
        }

        public Criteria andTheHandlerIn(List<String> values) {
            addCriterion("the_handler in", values, "theHandler");
            return (Criteria) this;
        }

        public Criteria andTheHandlerNotIn(List<String> values) {
            addCriterion("the_handler not in", values, "theHandler");
            return (Criteria) this;
        }

        public Criteria andTheHandlerBetween(String value1, String value2) {
            addCriterion("the_handler between", value1, value2, "theHandler");
            return (Criteria) this;
        }

        public Criteria andTheHandlerNotBetween(String value1, String value2) {
            addCriterion("the_handler not between", value1, value2, "theHandler");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table student_affairs
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table student_affairs
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}