package com.world.education.entity;

import java.io.Serializable;

public class StudentAccount implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_account.student_id
     *
     * @mbggenerated
     */
    private Integer studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_account.student_password
     *
     * @mbggenerated
     */
    private String studentPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_account.student_email
     *
     * @mbggenerated
     */
    private String studentEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_account.student_status
     *
     * @mbggenerated
     */
    private String studentStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student_account
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_account.student_id
     *
     * @return the value of student_account.student_id
     *
     * @mbggenerated
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_account.student_id
     *
     * @param studentId the value for student_account.student_id
     *
     * @mbggenerated
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_account.student_password
     *
     * @return the value of student_account.student_password
     *
     * @mbggenerated
     */
    public String getStudentPassword() {
        return studentPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_account.student_password
     *
     * @param studentPassword the value for student_account.student_password
     *
     * @mbggenerated
     */
    public void setStudentPassword(String studentPassword) {
        this.studentPassword = studentPassword == null ? null : studentPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_account.student_email
     *
     * @return the value of student_account.student_email
     *
     * @mbggenerated
     */
    public String getStudentEmail() {
        return studentEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_account.student_email
     *
     * @param studentEmail the value for student_account.student_email
     *
     * @mbggenerated
     */
    public void setStudentEmail(String studentEmail) {
        this.studentEmail = studentEmail == null ? null : studentEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_account.student_status
     *
     * @return the value of student_account.student_status
     *
     * @mbggenerated
     */
    public String getStudentStatus() {
        return studentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_account.student_status
     *
     * @param studentStatus the value for student_account.student_status
     *
     * @mbggenerated
     */
    public void setStudentStatus(String studentStatus) {
        this.studentStatus = studentStatus == null ? null : studentStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_account
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", studentId=").append(studentId);
        sb.append(", studentPassword=").append(studentPassword);
        sb.append(", studentEmail=").append(studentEmail);
        sb.append(", studentStatus=").append(studentStatus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}