package com.world.education.entity;

import java.io.Serializable;
import java.util.Date;

public class StudentAffairs implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_affairs.affairs_id
     *
     * @mbggenerated
     */
    private String affairsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_affairs.student_id
     *
     * @mbggenerated
     */
    private Integer studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_affairs.application_name
     *
     * @mbggenerated
     */
    private String applicationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_affairs.application_time
     *
     * @mbggenerated
     */
    private Date applicationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_affairs.affairs_title
     *
     * @mbggenerated
     */
    private String affairsTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_affairs.application_status
     *
     * @mbggenerated
     */
    private String applicationStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_affairs.the_handler
     *
     * @mbggenerated
     */
    private String theHandler;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_affairs.affairs_content
     *
     * @mbggenerated
     */
    private String affairsContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student_affairs
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_affairs.affairs_id
     *
     * @return the value of student_affairs.affairs_id
     *
     * @mbggenerated
     */
    public String getAffairsId() {
        return affairsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_affairs.affairs_id
     *
     * @param affairsId the value for student_affairs.affairs_id
     *
     * @mbggenerated
     */
    public void setAffairsId(String affairsId) {
        this.affairsId = affairsId == null ? null : affairsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_affairs.student_id
     *
     * @return the value of student_affairs.student_id
     *
     * @mbggenerated
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_affairs.student_id
     *
     * @param studentId the value for student_affairs.student_id
     *
     * @mbggenerated
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_affairs.application_name
     *
     * @return the value of student_affairs.application_name
     *
     * @mbggenerated
     */
    public String getApplicationName() {
        return applicationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_affairs.application_name
     *
     * @param applicationName the value for student_affairs.application_name
     *
     * @mbggenerated
     */
    public void setApplicationName(String applicationName) {
        this.applicationName = applicationName == null ? null : applicationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_affairs.application_time
     *
     * @return the value of student_affairs.application_time
     *
     * @mbggenerated
     */
    public Date getApplicationTime() {
        return applicationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_affairs.application_time
     *
     * @param applicationTime the value for student_affairs.application_time
     *
     * @mbggenerated
     */
    public void setApplicationTime(Date applicationTime) {
        this.applicationTime = applicationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_affairs.affairs_title
     *
     * @return the value of student_affairs.affairs_title
     *
     * @mbggenerated
     */
    public String getAffairsTitle() {
        return affairsTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_affairs.affairs_title
     *
     * @param affairsTitle the value for student_affairs.affairs_title
     *
     * @mbggenerated
     */
    public void setAffairsTitle(String affairsTitle) {
        this.affairsTitle = affairsTitle == null ? null : affairsTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_affairs.application_status
     *
     * @return the value of student_affairs.application_status
     *
     * @mbggenerated
     */
    public String getApplicationStatus() {
        return applicationStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_affairs.application_status
     *
     * @param applicationStatus the value for student_affairs.application_status
     *
     * @mbggenerated
     */
    public void setApplicationStatus(String applicationStatus) {
        this.applicationStatus = applicationStatus == null ? null : applicationStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_affairs.the_handler
     *
     * @return the value of student_affairs.the_handler
     *
     * @mbggenerated
     */
    public String getTheHandler() {
        return theHandler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_affairs.the_handler
     *
     * @param theHandler the value for student_affairs.the_handler
     *
     * @mbggenerated
     */
    public void setTheHandler(String theHandler) {
        this.theHandler = theHandler == null ? null : theHandler.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_affairs.affairs_content
     *
     * @return the value of student_affairs.affairs_content
     *
     * @mbggenerated
     */
    public String getAffairsContent() {
        return affairsContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_affairs.affairs_content
     *
     * @param affairsContent the value for student_affairs.affairs_content
     *
     * @mbggenerated
     */
    public void setAffairsContent(String affairsContent) {
        this.affairsContent = affairsContent == null ? null : affairsContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_affairs
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", affairsId=").append(affairsId);
        sb.append(", studentId=").append(studentId);
        sb.append(", applicationName=").append(applicationName);
        sb.append(", applicationTime=").append(applicationTime);
        sb.append(", affairsTitle=").append(affairsTitle);
        sb.append(", applicationStatus=").append(applicationStatus);
        sb.append(", theHandler=").append(theHandler);
        sb.append(", affairsContent=").append(affairsContent);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}