package com.world.education.entity;

import java.io.Serializable;
import java.util.Date;

public class TeacherInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.teacher_Id
     *
     * @mbggenerated
     */
    private Integer teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.teacher_Name
     *
     * @mbggenerated
     */
    private String teacherName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.teacher_Gender
     *
     * @mbggenerated
     */
    private String teacherGender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.teacher_Birthday
     *
     * @mbggenerated
     */
    private Date teacherBirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.teacher_Racial
     *
     * @mbggenerated
     */
    private String teacherRacial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.teacher_Graduate_School
     *
     * @mbggenerated
     */
    private String teacherGraduateSchool;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.teacher_Post
     *
     * @mbggenerated
     */
    private String teacherPost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.teacher_Native_Place
     *
     * @mbggenerated
     */
    private String teacherNativePlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.teacher_Address
     *
     * @mbggenerated
     */
    private String teacherAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.teacher_Phone
     *
     * @mbggenerated
     */
    private Integer teacherPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.teacher_Cell_Phone
     *
     * @mbggenerated
     */
    private Integer teacherCellPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.teacher_Email
     *
     * @mbggenerated
     */
    private String teacherEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.teacher_Photo
     *
     * @mbggenerated
     */
    private String teacherPhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table teacher_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_info.teacher_Id
     *
     * @return the value of teacher_info.teacher_Id
     *
     * @mbggenerated
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_info.teacher_Id
     *
     * @param teacherId the value for teacher_info.teacher_Id
     *
     * @mbggenerated
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_info.teacher_Name
     *
     * @return the value of teacher_info.teacher_Name
     *
     * @mbggenerated
     */
    public String getTeacherName() {
        return teacherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_info.teacher_Name
     *
     * @param teacherName the value for teacher_info.teacher_Name
     *
     * @mbggenerated
     */
    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName == null ? null : teacherName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_info.teacher_Gender
     *
     * @return the value of teacher_info.teacher_Gender
     *
     * @mbggenerated
     */
    public String getTeacherGender() {
        return teacherGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_info.teacher_Gender
     *
     * @param teacherGender the value for teacher_info.teacher_Gender
     *
     * @mbggenerated
     */
    public void setTeacherGender(String teacherGender) {
        this.teacherGender = teacherGender == null ? null : teacherGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_info.teacher_Birthday
     *
     * @return the value of teacher_info.teacher_Birthday
     *
     * @mbggenerated
     */
    public Date getTeacherBirthday() {
        return teacherBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_info.teacher_Birthday
     *
     * @param teacherBirthday the value for teacher_info.teacher_Birthday
     *
     * @mbggenerated
     */
    public void setTeacherBirthday(Date teacherBirthday) {
        this.teacherBirthday = teacherBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_info.teacher_Racial
     *
     * @return the value of teacher_info.teacher_Racial
     *
     * @mbggenerated
     */
    public String getTeacherRacial() {
        return teacherRacial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_info.teacher_Racial
     *
     * @param teacherRacial the value for teacher_info.teacher_Racial
     *
     * @mbggenerated
     */
    public void setTeacherRacial(String teacherRacial) {
        this.teacherRacial = teacherRacial == null ? null : teacherRacial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_info.teacher_Graduate_School
     *
     * @return the value of teacher_info.teacher_Graduate_School
     *
     * @mbggenerated
     */
    public String getTeacherGraduateSchool() {
        return teacherGraduateSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_info.teacher_Graduate_School
     *
     * @param teacherGraduateSchool the value for teacher_info.teacher_Graduate_School
     *
     * @mbggenerated
     */
    public void setTeacherGraduateSchool(String teacherGraduateSchool) {
        this.teacherGraduateSchool = teacherGraduateSchool == null ? null : teacherGraduateSchool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_info.teacher_Post
     *
     * @return the value of teacher_info.teacher_Post
     *
     * @mbggenerated
     */
    public String getTeacherPost() {
        return teacherPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_info.teacher_Post
     *
     * @param teacherPost the value for teacher_info.teacher_Post
     *
     * @mbggenerated
     */
    public void setTeacherPost(String teacherPost) {
        this.teacherPost = teacherPost == null ? null : teacherPost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_info.teacher_Native_Place
     *
     * @return the value of teacher_info.teacher_Native_Place
     *
     * @mbggenerated
     */
    public String getTeacherNativePlace() {
        return teacherNativePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_info.teacher_Native_Place
     *
     * @param teacherNativePlace the value for teacher_info.teacher_Native_Place
     *
     * @mbggenerated
     */
    public void setTeacherNativePlace(String teacherNativePlace) {
        this.teacherNativePlace = teacherNativePlace == null ? null : teacherNativePlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_info.teacher_Address
     *
     * @return the value of teacher_info.teacher_Address
     *
     * @mbggenerated
     */
    public String getTeacherAddress() {
        return teacherAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_info.teacher_Address
     *
     * @param teacherAddress the value for teacher_info.teacher_Address
     *
     * @mbggenerated
     */
    public void setTeacherAddress(String teacherAddress) {
        this.teacherAddress = teacherAddress == null ? null : teacherAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_info.teacher_Phone
     *
     * @return the value of teacher_info.teacher_Phone
     *
     * @mbggenerated
     */
    public Integer getTeacherPhone() {
        return teacherPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_info.teacher_Phone
     *
     * @param teacherPhone the value for teacher_info.teacher_Phone
     *
     * @mbggenerated
     */
    public void setTeacherPhone(Integer teacherPhone) {
        this.teacherPhone = teacherPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_info.teacher_Cell_Phone
     *
     * @return the value of teacher_info.teacher_Cell_Phone
     *
     * @mbggenerated
     */
    public Integer getTeacherCellPhone() {
        return teacherCellPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_info.teacher_Cell_Phone
     *
     * @param teacherCellPhone the value for teacher_info.teacher_Cell_Phone
     *
     * @mbggenerated
     */
    public void setTeacherCellPhone(Integer teacherCellPhone) {
        this.teacherCellPhone = teacherCellPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_info.teacher_Email
     *
     * @return the value of teacher_info.teacher_Email
     *
     * @mbggenerated
     */
    public String getTeacherEmail() {
        return teacherEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_info.teacher_Email
     *
     * @param teacherEmail the value for teacher_info.teacher_Email
     *
     * @mbggenerated
     */
    public void setTeacherEmail(String teacherEmail) {
        this.teacherEmail = teacherEmail == null ? null : teacherEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_info.teacher_Photo
     *
     * @return the value of teacher_info.teacher_Photo
     *
     * @mbggenerated
     */
    public String getTeacherPhoto() {
        return teacherPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_info.teacher_Photo
     *
     * @param teacherPhoto the value for teacher_info.teacher_Photo
     *
     * @mbggenerated
     */
    public void setTeacherPhoto(String teacherPhoto) {
        this.teacherPhoto = teacherPhoto == null ? null : teacherPhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", teacherId=").append(teacherId);
        sb.append(", teacherName=").append(teacherName);
        sb.append(", teacherGender=").append(teacherGender);
        sb.append(", teacherBirthday=").append(teacherBirthday);
        sb.append(", teacherRacial=").append(teacherRacial);
        sb.append(", teacherGraduateSchool=").append(teacherGraduateSchool);
        sb.append(", teacherPost=").append(teacherPost);
        sb.append(", teacherNativePlace=").append(teacherNativePlace);
        sb.append(", teacherAddress=").append(teacherAddress);
        sb.append(", teacherPhone=").append(teacherPhone);
        sb.append(", teacherCellPhone=").append(teacherCellPhone);
        sb.append(", teacherEmail=").append(teacherEmail);
        sb.append(", teacherPhoto=").append(teacherPhoto);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}