package com.world.education.mapper;

import com.world.education.entity.AdminAccount;
import com.world.education.entity.AdminAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdminAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_account
     *
     * @mbggenerated
     */
    int countByExample(AdminAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_account
     *
     * @mbggenerated
     */
    int deleteByExample(AdminAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_account
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_account
     *
     * @mbggenerated
     */
    int insert(AdminAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_account
     *
     * @mbggenerated
     */
    int insertSelective(AdminAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_account
     *
     * @mbggenerated
     */
    List<AdminAccount> selectByExample(AdminAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_account
     *
     * @mbggenerated
     */
    AdminAccount selectByPrimaryKey(Integer adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_account
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AdminAccount record, @Param("example") AdminAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_account
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AdminAccount record, @Param("example") AdminAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AdminAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AdminAccount record);
}