package com.world.education.mapper;

import com.world.education.entity.ElectiveData;
import com.world.education.entity.ElectiveDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ElectiveDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table elective_table
     *
     * @mbggenerated
     */
    int countByExample(ElectiveDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table elective_table
     *
     * @mbggenerated
     */
    int deleteByExample(ElectiveDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table elective_table
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer electiveId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table elective_table
     *
     * @mbggenerated
     */
    int insert(ElectiveData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table elective_table
     *
     * @mbggenerated
     */
    int insertSelective(ElectiveData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table elective_table
     *
     * @mbggenerated
     */
    List<ElectiveData> selectByExample(ElectiveDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table elective_table
     *
     * @mbggenerated
     */
    ElectiveData selectByPrimaryKey(Integer electiveId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table elective_table
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ElectiveData record, @Param("example") ElectiveDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table elective_table
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ElectiveData record, @Param("example") ElectiveDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table elective_table
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ElectiveData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table elective_table
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ElectiveData record);
}