package com.education.system.mapper;

import com.education.system.entity.StudentAffairs;
import com.education.system.entity.StudentAffairsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface StudentAffairsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_affairs
     *
     * @mbggenerated
     */
    int countByExample(StudentAffairsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_affairs
     *
     * @mbggenerated
     */
    int deleteByExample(StudentAffairsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_affairs
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer affairsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_affairs
     *
     * @mbggenerated
     */
    int insert(StudentAffairs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_affairs
     *
     * @mbggenerated
     */
    int insertSelective(StudentAffairs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_affairs
     *
     * @mbggenerated
     */
    List<StudentAffairs> selectByExampleWithBLOBs(StudentAffairsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_affairs
     *
     * @mbggenerated
     */
    List<StudentAffairs> selectByExample(StudentAffairsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_affairs
     *
     * @mbggenerated
     */
    StudentAffairs selectByPrimaryKey(Integer affairsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_affairs
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") StudentAffairs record, @Param("example") StudentAffairsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_affairs
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") StudentAffairs record, @Param("example") StudentAffairsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_affairs
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") StudentAffairs record, @Param("example") StudentAffairsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_affairs
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StudentAffairs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_affairs
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(StudentAffairs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_affairs
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StudentAffairs record);
}