package com.education.system.mapper;

import com.education.system.entity.TeacherAccount;
import com.education.system.entity.TeacherAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TeacherAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_account
     *
     * @mbggenerated
     */
    int countByExample(TeacherAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_account
     *
     * @mbggenerated
     */
    int deleteByExample(TeacherAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_account
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer teacherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_account
     *
     * @mbggenerated
     */
    int insert(TeacherAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_account
     *
     * @mbggenerated
     */
    int insertSelective(TeacherAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_account
     *
     * @mbggenerated
     */
    List<TeacherAccount> selectByExample(TeacherAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_account
     *
     * @mbggenerated
     */
    TeacherAccount selectByPrimaryKey(Integer teacherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_account
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TeacherAccount record, @Param("example") TeacherAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_account
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TeacherAccount record, @Param("example") TeacherAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TeacherAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TeacherAccount record);
}