package com.education.system.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class StudentInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student_info
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student_info
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student_info
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbggenerated
     */
    public StudentInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table student_info
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andStudentIdIsNull() {
            addCriterion("student_id is null");
            return (Criteria) this;
        }

        public Criteria andStudentIdIsNotNull() {
            addCriterion("student_id is not null");
            return (Criteria) this;
        }

        public Criteria andStudentIdEqualTo(Integer value) {
            addCriterion("student_id =", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotEqualTo(Integer value) {
            addCriterion("student_id <>", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdGreaterThan(Integer value) {
            addCriterion("student_id >", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("student_id >=", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLessThan(Integer value) {
            addCriterion("student_id <", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLessThanOrEqualTo(Integer value) {
            addCriterion("student_id <=", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdIn(List<Integer> values) {
            addCriterion("student_id in", values, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotIn(List<Integer> values) {
            addCriterion("student_id not in", values, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdBetween(Integer value1, Integer value2) {
            addCriterion("student_id between", value1, value2, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotBetween(Integer value1, Integer value2) {
            addCriterion("student_id not between", value1, value2, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentNameIsNull() {
            addCriterion("student_name is null");
            return (Criteria) this;
        }

        public Criteria andStudentNameIsNotNull() {
            addCriterion("student_name is not null");
            return (Criteria) this;
        }

        public Criteria andStudentNameEqualTo(String value) {
            addCriterion("student_name =", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameNotEqualTo(String value) {
            addCriterion("student_name <>", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameGreaterThan(String value) {
            addCriterion("student_name >", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameGreaterThanOrEqualTo(String value) {
            addCriterion("student_name >=", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameLessThan(String value) {
            addCriterion("student_name <", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameLessThanOrEqualTo(String value) {
            addCriterion("student_name <=", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameLike(String value) {
            addCriterion("student_name like", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameNotLike(String value) {
            addCriterion("student_name not like", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameIn(List<String> values) {
            addCriterion("student_name in", values, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameNotIn(List<String> values) {
            addCriterion("student_name not in", values, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameBetween(String value1, String value2) {
            addCriterion("student_name between", value1, value2, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameNotBetween(String value1, String value2) {
            addCriterion("student_name not between", value1, value2, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentGenderIsNull() {
            addCriterion("student_gender is null");
            return (Criteria) this;
        }

        public Criteria andStudentGenderIsNotNull() {
            addCriterion("student_gender is not null");
            return (Criteria) this;
        }

        public Criteria andStudentGenderEqualTo(String value) {
            addCriterion("student_gender =", value, "studentGender");
            return (Criteria) this;
        }

        public Criteria andStudentGenderNotEqualTo(String value) {
            addCriterion("student_gender <>", value, "studentGender");
            return (Criteria) this;
        }

        public Criteria andStudentGenderGreaterThan(String value) {
            addCriterion("student_gender >", value, "studentGender");
            return (Criteria) this;
        }

        public Criteria andStudentGenderGreaterThanOrEqualTo(String value) {
            addCriterion("student_gender >=", value, "studentGender");
            return (Criteria) this;
        }

        public Criteria andStudentGenderLessThan(String value) {
            addCriterion("student_gender <", value, "studentGender");
            return (Criteria) this;
        }

        public Criteria andStudentGenderLessThanOrEqualTo(String value) {
            addCriterion("student_gender <=", value, "studentGender");
            return (Criteria) this;
        }

        public Criteria andStudentGenderLike(String value) {
            addCriterion("student_gender like", value, "studentGender");
            return (Criteria) this;
        }

        public Criteria andStudentGenderNotLike(String value) {
            addCriterion("student_gender not like", value, "studentGender");
            return (Criteria) this;
        }

        public Criteria andStudentGenderIn(List<String> values) {
            addCriterion("student_gender in", values, "studentGender");
            return (Criteria) this;
        }

        public Criteria andStudentGenderNotIn(List<String> values) {
            addCriterion("student_gender not in", values, "studentGender");
            return (Criteria) this;
        }

        public Criteria andStudentGenderBetween(String value1, String value2) {
            addCriterion("student_gender between", value1, value2, "studentGender");
            return (Criteria) this;
        }

        public Criteria andStudentGenderNotBetween(String value1, String value2) {
            addCriterion("student_gender not between", value1, value2, "studentGender");
            return (Criteria) this;
        }

        public Criteria andStudentBirthdayIsNull() {
            addCriterion("student_birthday is null");
            return (Criteria) this;
        }

        public Criteria andStudentBirthdayIsNotNull() {
            addCriterion("student_birthday is not null");
            return (Criteria) this;
        }

        public Criteria andStudentBirthdayEqualTo(Date value) {
            addCriterionForJDBCDate("student_birthday =", value, "studentBirthday");
            return (Criteria) this;
        }

        public Criteria andStudentBirthdayNotEqualTo(Date value) {
            addCriterionForJDBCDate("student_birthday <>", value, "studentBirthday");
            return (Criteria) this;
        }

        public Criteria andStudentBirthdayGreaterThan(Date value) {
            addCriterionForJDBCDate("student_birthday >", value, "studentBirthday");
            return (Criteria) this;
        }

        public Criteria andStudentBirthdayGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("student_birthday >=", value, "studentBirthday");
            return (Criteria) this;
        }

        public Criteria andStudentBirthdayLessThan(Date value) {
            addCriterionForJDBCDate("student_birthday <", value, "studentBirthday");
            return (Criteria) this;
        }

        public Criteria andStudentBirthdayLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("student_birthday <=", value, "studentBirthday");
            return (Criteria) this;
        }

        public Criteria andStudentBirthdayIn(List<Date> values) {
            addCriterionForJDBCDate("student_birthday in", values, "studentBirthday");
            return (Criteria) this;
        }

        public Criteria andStudentBirthdayNotIn(List<Date> values) {
            addCriterionForJDBCDate("student_birthday not in", values, "studentBirthday");
            return (Criteria) this;
        }

        public Criteria andStudentBirthdayBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("student_birthday between", value1, value2, "studentBirthday");
            return (Criteria) this;
        }

        public Criteria andStudentBirthdayNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("student_birthday not between", value1, value2, "studentBirthday");
            return (Criteria) this;
        }

        public Criteria andStudentRacialIsNull() {
            addCriterion("student_racial is null");
            return (Criteria) this;
        }

        public Criteria andStudentRacialIsNotNull() {
            addCriterion("student_racial is not null");
            return (Criteria) this;
        }

        public Criteria andStudentRacialEqualTo(String value) {
            addCriterion("student_racial =", value, "studentRacial");
            return (Criteria) this;
        }

        public Criteria andStudentRacialNotEqualTo(String value) {
            addCriterion("student_racial <>", value, "studentRacial");
            return (Criteria) this;
        }

        public Criteria andStudentRacialGreaterThan(String value) {
            addCriterion("student_racial >", value, "studentRacial");
            return (Criteria) this;
        }

        public Criteria andStudentRacialGreaterThanOrEqualTo(String value) {
            addCriterion("student_racial >=", value, "studentRacial");
            return (Criteria) this;
        }

        public Criteria andStudentRacialLessThan(String value) {
            addCriterion("student_racial <", value, "studentRacial");
            return (Criteria) this;
        }

        public Criteria andStudentRacialLessThanOrEqualTo(String value) {
            addCriterion("student_racial <=", value, "studentRacial");
            return (Criteria) this;
        }

        public Criteria andStudentRacialLike(String value) {
            addCriterion("student_racial like", value, "studentRacial");
            return (Criteria) this;
        }

        public Criteria andStudentRacialNotLike(String value) {
            addCriterion("student_racial not like", value, "studentRacial");
            return (Criteria) this;
        }

        public Criteria andStudentRacialIn(List<String> values) {
            addCriterion("student_racial in", values, "studentRacial");
            return (Criteria) this;
        }

        public Criteria andStudentRacialNotIn(List<String> values) {
            addCriterion("student_racial not in", values, "studentRacial");
            return (Criteria) this;
        }

        public Criteria andStudentRacialBetween(String value1, String value2) {
            addCriterion("student_racial between", value1, value2, "studentRacial");
            return (Criteria) this;
        }

        public Criteria andStudentRacialNotBetween(String value1, String value2) {
            addCriterion("student_racial not between", value1, value2, "studentRacial");
            return (Criteria) this;
        }

        public Criteria andStudentNativePlaceIsNull() {
            addCriterion("student_native_place is null");
            return (Criteria) this;
        }

        public Criteria andStudentNativePlaceIsNotNull() {
            addCriterion("student_native_place is not null");
            return (Criteria) this;
        }

        public Criteria andStudentNativePlaceEqualTo(String value) {
            addCriterion("student_native_place =", value, "studentNativePlace");
            return (Criteria) this;
        }

        public Criteria andStudentNativePlaceNotEqualTo(String value) {
            addCriterion("student_native_place <>", value, "studentNativePlace");
            return (Criteria) this;
        }

        public Criteria andStudentNativePlaceGreaterThan(String value) {
            addCriterion("student_native_place >", value, "studentNativePlace");
            return (Criteria) this;
        }

        public Criteria andStudentNativePlaceGreaterThanOrEqualTo(String value) {
            addCriterion("student_native_place >=", value, "studentNativePlace");
            return (Criteria) this;
        }

        public Criteria andStudentNativePlaceLessThan(String value) {
            addCriterion("student_native_place <", value, "studentNativePlace");
            return (Criteria) this;
        }

        public Criteria andStudentNativePlaceLessThanOrEqualTo(String value) {
            addCriterion("student_native_place <=", value, "studentNativePlace");
            return (Criteria) this;
        }

        public Criteria andStudentNativePlaceLike(String value) {
            addCriterion("student_native_place like", value, "studentNativePlace");
            return (Criteria) this;
        }

        public Criteria andStudentNativePlaceNotLike(String value) {
            addCriterion("student_native_place not like", value, "studentNativePlace");
            return (Criteria) this;
        }

        public Criteria andStudentNativePlaceIn(List<String> values) {
            addCriterion("student_native_place in", values, "studentNativePlace");
            return (Criteria) this;
        }

        public Criteria andStudentNativePlaceNotIn(List<String> values) {
            addCriterion("student_native_place not in", values, "studentNativePlace");
            return (Criteria) this;
        }

        public Criteria andStudentNativePlaceBetween(String value1, String value2) {
            addCriterion("student_native_place between", value1, value2, "studentNativePlace");
            return (Criteria) this;
        }

        public Criteria andStudentNativePlaceNotBetween(String value1, String value2) {
            addCriterion("student_native_place not between", value1, value2, "studentNativePlace");
            return (Criteria) this;
        }

        public Criteria andStudentJoinTimeIsNull() {
            addCriterion("student_join_time is null");
            return (Criteria) this;
        }

        public Criteria andStudentJoinTimeIsNotNull() {
            addCriterion("student_join_time is not null");
            return (Criteria) this;
        }

        public Criteria andStudentJoinTimeEqualTo(Date value) {
            addCriterionForJDBCDate("student_join_time =", value, "studentJoinTime");
            return (Criteria) this;
        }

        public Criteria andStudentJoinTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("student_join_time <>", value, "studentJoinTime");
            return (Criteria) this;
        }

        public Criteria andStudentJoinTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("student_join_time >", value, "studentJoinTime");
            return (Criteria) this;
        }

        public Criteria andStudentJoinTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("student_join_time >=", value, "studentJoinTime");
            return (Criteria) this;
        }

        public Criteria andStudentJoinTimeLessThan(Date value) {
            addCriterionForJDBCDate("student_join_time <", value, "studentJoinTime");
            return (Criteria) this;
        }

        public Criteria andStudentJoinTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("student_join_time <=", value, "studentJoinTime");
            return (Criteria) this;
        }

        public Criteria andStudentJoinTimeIn(List<Date> values) {
            addCriterionForJDBCDate("student_join_time in", values, "studentJoinTime");
            return (Criteria) this;
        }

        public Criteria andStudentJoinTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("student_join_time not in", values, "studentJoinTime");
            return (Criteria) this;
        }

        public Criteria andStudentJoinTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("student_join_time between", value1, value2, "studentJoinTime");
            return (Criteria) this;
        }

        public Criteria andStudentJoinTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("student_join_time not between", value1, value2, "studentJoinTime");
            return (Criteria) this;
        }

        public Criteria andStudentMajorIsNull() {
            addCriterion("student_major is null");
            return (Criteria) this;
        }

        public Criteria andStudentMajorIsNotNull() {
            addCriterion("student_major is not null");
            return (Criteria) this;
        }

        public Criteria andStudentMajorEqualTo(String value) {
            addCriterion("student_major =", value, "studentMajor");
            return (Criteria) this;
        }

        public Criteria andStudentMajorNotEqualTo(String value) {
            addCriterion("student_major <>", value, "studentMajor");
            return (Criteria) this;
        }

        public Criteria andStudentMajorGreaterThan(String value) {
            addCriterion("student_major >", value, "studentMajor");
            return (Criteria) this;
        }

        public Criteria andStudentMajorGreaterThanOrEqualTo(String value) {
            addCriterion("student_major >=", value, "studentMajor");
            return (Criteria) this;
        }

        public Criteria andStudentMajorLessThan(String value) {
            addCriterion("student_major <", value, "studentMajor");
            return (Criteria) this;
        }

        public Criteria andStudentMajorLessThanOrEqualTo(String value) {
            addCriterion("student_major <=", value, "studentMajor");
            return (Criteria) this;
        }

        public Criteria andStudentMajorLike(String value) {
            addCriterion("student_major like", value, "studentMajor");
            return (Criteria) this;
        }

        public Criteria andStudentMajorNotLike(String value) {
            addCriterion("student_major not like", value, "studentMajor");
            return (Criteria) this;
        }

        public Criteria andStudentMajorIn(List<String> values) {
            addCriterion("student_major in", values, "studentMajor");
            return (Criteria) this;
        }

        public Criteria andStudentMajorNotIn(List<String> values) {
            addCriterion("student_major not in", values, "studentMajor");
            return (Criteria) this;
        }

        public Criteria andStudentMajorBetween(String value1, String value2) {
            addCriterion("student_major between", value1, value2, "studentMajor");
            return (Criteria) this;
        }

        public Criteria andStudentMajorNotBetween(String value1, String value2) {
            addCriterion("student_major not between", value1, value2, "studentMajor");
            return (Criteria) this;
        }

        public Criteria andStudentClassIsNull() {
            addCriterion("student_class is null");
            return (Criteria) this;
        }

        public Criteria andStudentClassIsNotNull() {
            addCriterion("student_class is not null");
            return (Criteria) this;
        }

        public Criteria andStudentClassEqualTo(String value) {
            addCriterion("student_class =", value, "studentClass");
            return (Criteria) this;
        }

        public Criteria andStudentClassNotEqualTo(String value) {
            addCriterion("student_class <>", value, "studentClass");
            return (Criteria) this;
        }

        public Criteria andStudentClassGreaterThan(String value) {
            addCriterion("student_class >", value, "studentClass");
            return (Criteria) this;
        }

        public Criteria andStudentClassGreaterThanOrEqualTo(String value) {
            addCriterion("student_class >=", value, "studentClass");
            return (Criteria) this;
        }

        public Criteria andStudentClassLessThan(String value) {
            addCriterion("student_class <", value, "studentClass");
            return (Criteria) this;
        }

        public Criteria andStudentClassLessThanOrEqualTo(String value) {
            addCriterion("student_class <=", value, "studentClass");
            return (Criteria) this;
        }

        public Criteria andStudentClassLike(String value) {
            addCriterion("student_class like", value, "studentClass");
            return (Criteria) this;
        }

        public Criteria andStudentClassNotLike(String value) {
            addCriterion("student_class not like", value, "studentClass");
            return (Criteria) this;
        }

        public Criteria andStudentClassIn(List<String> values) {
            addCriterion("student_class in", values, "studentClass");
            return (Criteria) this;
        }

        public Criteria andStudentClassNotIn(List<String> values) {
            addCriterion("student_class not in", values, "studentClass");
            return (Criteria) this;
        }

        public Criteria andStudentClassBetween(String value1, String value2) {
            addCriterion("student_class between", value1, value2, "studentClass");
            return (Criteria) this;
        }

        public Criteria andStudentClassNotBetween(String value1, String value2) {
            addCriterion("student_class not between", value1, value2, "studentClass");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneIsNull() {
            addCriterion("student_phone is null");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneIsNotNull() {
            addCriterion("student_phone is not null");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneEqualTo(Integer value) {
            addCriterion("student_phone =", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneNotEqualTo(Integer value) {
            addCriterion("student_phone <>", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneGreaterThan(Integer value) {
            addCriterion("student_phone >", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneGreaterThanOrEqualTo(Integer value) {
            addCriterion("student_phone >=", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneLessThan(Integer value) {
            addCriterion("student_phone <", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneLessThanOrEqualTo(Integer value) {
            addCriterion("student_phone <=", value, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneIn(List<Integer> values) {
            addCriterion("student_phone in", values, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneNotIn(List<Integer> values) {
            addCriterion("student_phone not in", values, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneBetween(Integer value1, Integer value2) {
            addCriterion("student_phone between", value1, value2, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentPhoneNotBetween(Integer value1, Integer value2) {
            addCriterion("student_phone not between", value1, value2, "studentPhone");
            return (Criteria) this;
        }

        public Criteria andStudentCellphoneIsNull() {
            addCriterion("student_cellphone is null");
            return (Criteria) this;
        }

        public Criteria andStudentCellphoneIsNotNull() {
            addCriterion("student_cellphone is not null");
            return (Criteria) this;
        }

        public Criteria andStudentCellphoneEqualTo(String value) {
            addCriterion("student_cellphone =", value, "studentCellphone");
            return (Criteria) this;
        }

        public Criteria andStudentCellphoneNotEqualTo(String value) {
            addCriterion("student_cellphone <>", value, "studentCellphone");
            return (Criteria) this;
        }

        public Criteria andStudentCellphoneGreaterThan(String value) {
            addCriterion("student_cellphone >", value, "studentCellphone");
            return (Criteria) this;
        }

        public Criteria andStudentCellphoneGreaterThanOrEqualTo(String value) {
            addCriterion("student_cellphone >=", value, "studentCellphone");
            return (Criteria) this;
        }

        public Criteria andStudentCellphoneLessThan(String value) {
            addCriterion("student_cellphone <", value, "studentCellphone");
            return (Criteria) this;
        }

        public Criteria andStudentCellphoneLessThanOrEqualTo(String value) {
            addCriterion("student_cellphone <=", value, "studentCellphone");
            return (Criteria) this;
        }

        public Criteria andStudentCellphoneLike(String value) {
            addCriterion("student_cellphone like", value, "studentCellphone");
            return (Criteria) this;
        }

        public Criteria andStudentCellphoneNotLike(String value) {
            addCriterion("student_cellphone not like", value, "studentCellphone");
            return (Criteria) this;
        }

        public Criteria andStudentCellphoneIn(List<String> values) {
            addCriterion("student_cellphone in", values, "studentCellphone");
            return (Criteria) this;
        }

        public Criteria andStudentCellphoneNotIn(List<String> values) {
            addCriterion("student_cellphone not in", values, "studentCellphone");
            return (Criteria) this;
        }

        public Criteria andStudentCellphoneBetween(String value1, String value2) {
            addCriterion("student_cellphone between", value1, value2, "studentCellphone");
            return (Criteria) this;
        }

        public Criteria andStudentCellphoneNotBetween(String value1, String value2) {
            addCriterion("student_cellphone not between", value1, value2, "studentCellphone");
            return (Criteria) this;
        }

        public Criteria andStudentAddressIsNull() {
            addCriterion("student_address is null");
            return (Criteria) this;
        }

        public Criteria andStudentAddressIsNotNull() {
            addCriterion("student_address is not null");
            return (Criteria) this;
        }

        public Criteria andStudentAddressEqualTo(String value) {
            addCriterion("student_address =", value, "studentAddress");
            return (Criteria) this;
        }

        public Criteria andStudentAddressNotEqualTo(String value) {
            addCriterion("student_address <>", value, "studentAddress");
            return (Criteria) this;
        }

        public Criteria andStudentAddressGreaterThan(String value) {
            addCriterion("student_address >", value, "studentAddress");
            return (Criteria) this;
        }

        public Criteria andStudentAddressGreaterThanOrEqualTo(String value) {
            addCriterion("student_address >=", value, "studentAddress");
            return (Criteria) this;
        }

        public Criteria andStudentAddressLessThan(String value) {
            addCriterion("student_address <", value, "studentAddress");
            return (Criteria) this;
        }

        public Criteria andStudentAddressLessThanOrEqualTo(String value) {
            addCriterion("student_address <=", value, "studentAddress");
            return (Criteria) this;
        }

        public Criteria andStudentAddressLike(String value) {
            addCriterion("student_address like", value, "studentAddress");
            return (Criteria) this;
        }

        public Criteria andStudentAddressNotLike(String value) {
            addCriterion("student_address not like", value, "studentAddress");
            return (Criteria) this;
        }

        public Criteria andStudentAddressIn(List<String> values) {
            addCriterion("student_address in", values, "studentAddress");
            return (Criteria) this;
        }

        public Criteria andStudentAddressNotIn(List<String> values) {
            addCriterion("student_address not in", values, "studentAddress");
            return (Criteria) this;
        }

        public Criteria andStudentAddressBetween(String value1, String value2) {
            addCriterion("student_address between", value1, value2, "studentAddress");
            return (Criteria) this;
        }

        public Criteria andStudentAddressNotBetween(String value1, String value2) {
            addCriterion("student_address not between", value1, value2, "studentAddress");
            return (Criteria) this;
        }

        public Criteria andStudentEmergencyContactIsNull() {
            addCriterion("student_emergency_contact is null");
            return (Criteria) this;
        }

        public Criteria andStudentEmergencyContactIsNotNull() {
            addCriterion("student_emergency_contact is not null");
            return (Criteria) this;
        }

        public Criteria andStudentEmergencyContactEqualTo(String value) {
            addCriterion("student_emergency_contact =", value, "studentEmergencyContact");
            return (Criteria) this;
        }

        public Criteria andStudentEmergencyContactNotEqualTo(String value) {
            addCriterion("student_emergency_contact <>", value, "studentEmergencyContact");
            return (Criteria) this;
        }

        public Criteria andStudentEmergencyContactGreaterThan(String value) {
            addCriterion("student_emergency_contact >", value, "studentEmergencyContact");
            return (Criteria) this;
        }

        public Criteria andStudentEmergencyContactGreaterThanOrEqualTo(String value) {
            addCriterion("student_emergency_contact >=", value, "studentEmergencyContact");
            return (Criteria) this;
        }

        public Criteria andStudentEmergencyContactLessThan(String value) {
            addCriterion("student_emergency_contact <", value, "studentEmergencyContact");
            return (Criteria) this;
        }

        public Criteria andStudentEmergencyContactLessThanOrEqualTo(String value) {
            addCriterion("student_emergency_contact <=", value, "studentEmergencyContact");
            return (Criteria) this;
        }

        public Criteria andStudentEmergencyContactLike(String value) {
            addCriterion("student_emergency_contact like", value, "studentEmergencyContact");
            return (Criteria) this;
        }

        public Criteria andStudentEmergencyContactNotLike(String value) {
            addCriterion("student_emergency_contact not like", value, "studentEmergencyContact");
            return (Criteria) this;
        }

        public Criteria andStudentEmergencyContactIn(List<String> values) {
            addCriterion("student_emergency_contact in", values, "studentEmergencyContact");
            return (Criteria) this;
        }

        public Criteria andStudentEmergencyContactNotIn(List<String> values) {
            addCriterion("student_emergency_contact not in", values, "studentEmergencyContact");
            return (Criteria) this;
        }

        public Criteria andStudentEmergencyContactBetween(String value1, String value2) {
            addCriterion("student_emergency_contact between", value1, value2, "studentEmergencyContact");
            return (Criteria) this;
        }

        public Criteria andStudentEmergencyContactNotBetween(String value1, String value2) {
            addCriterion("student_emergency_contact not between", value1, value2, "studentEmergencyContact");
            return (Criteria) this;
        }

        public Criteria andStudentContactPhoneIsNull() {
            addCriterion("student_contact_phone is null");
            return (Criteria) this;
        }

        public Criteria andStudentContactPhoneIsNotNull() {
            addCriterion("student_contact_phone is not null");
            return (Criteria) this;
        }

        public Criteria andStudentContactPhoneEqualTo(String value) {
            addCriterion("student_contact_phone =", value, "studentContactPhone");
            return (Criteria) this;
        }

        public Criteria andStudentContactPhoneNotEqualTo(String value) {
            addCriterion("student_contact_phone <>", value, "studentContactPhone");
            return (Criteria) this;
        }

        public Criteria andStudentContactPhoneGreaterThan(String value) {
            addCriterion("student_contact_phone >", value, "studentContactPhone");
            return (Criteria) this;
        }

        public Criteria andStudentContactPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("student_contact_phone >=", value, "studentContactPhone");
            return (Criteria) this;
        }

        public Criteria andStudentContactPhoneLessThan(String value) {
            addCriterion("student_contact_phone <", value, "studentContactPhone");
            return (Criteria) this;
        }

        public Criteria andStudentContactPhoneLessThanOrEqualTo(String value) {
            addCriterion("student_contact_phone <=", value, "studentContactPhone");
            return (Criteria) this;
        }

        public Criteria andStudentContactPhoneLike(String value) {
            addCriterion("student_contact_phone like", value, "studentContactPhone");
            return (Criteria) this;
        }

        public Criteria andStudentContactPhoneNotLike(String value) {
            addCriterion("student_contact_phone not like", value, "studentContactPhone");
            return (Criteria) this;
        }

        public Criteria andStudentContactPhoneIn(List<String> values) {
            addCriterion("student_contact_phone in", values, "studentContactPhone");
            return (Criteria) this;
        }

        public Criteria andStudentContactPhoneNotIn(List<String> values) {
            addCriterion("student_contact_phone not in", values, "studentContactPhone");
            return (Criteria) this;
        }

        public Criteria andStudentContactPhoneBetween(String value1, String value2) {
            addCriterion("student_contact_phone between", value1, value2, "studentContactPhone");
            return (Criteria) this;
        }

        public Criteria andStudentContactPhoneNotBetween(String value1, String value2) {
            addCriterion("student_contact_phone not between", value1, value2, "studentContactPhone");
            return (Criteria) this;
        }

        public Criteria andStudentEmailIsNull() {
            addCriterion("student_email is null");
            return (Criteria) this;
        }

        public Criteria andStudentEmailIsNotNull() {
            addCriterion("student_email is not null");
            return (Criteria) this;
        }

        public Criteria andStudentEmailEqualTo(String value) {
            addCriterion("student_email =", value, "studentEmail");
            return (Criteria) this;
        }

        public Criteria andStudentEmailNotEqualTo(String value) {
            addCriterion("student_email <>", value, "studentEmail");
            return (Criteria) this;
        }

        public Criteria andStudentEmailGreaterThan(String value) {
            addCriterion("student_email >", value, "studentEmail");
            return (Criteria) this;
        }

        public Criteria andStudentEmailGreaterThanOrEqualTo(String value) {
            addCriterion("student_email >=", value, "studentEmail");
            return (Criteria) this;
        }

        public Criteria andStudentEmailLessThan(String value) {
            addCriterion("student_email <", value, "studentEmail");
            return (Criteria) this;
        }

        public Criteria andStudentEmailLessThanOrEqualTo(String value) {
            addCriterion("student_email <=", value, "studentEmail");
            return (Criteria) this;
        }

        public Criteria andStudentEmailLike(String value) {
            addCriterion("student_email like", value, "studentEmail");
            return (Criteria) this;
        }

        public Criteria andStudentEmailNotLike(String value) {
            addCriterion("student_email not like", value, "studentEmail");
            return (Criteria) this;
        }

        public Criteria andStudentEmailIn(List<String> values) {
            addCriterion("student_email in", values, "studentEmail");
            return (Criteria) this;
        }

        public Criteria andStudentEmailNotIn(List<String> values) {
            addCriterion("student_email not in", values, "studentEmail");
            return (Criteria) this;
        }

        public Criteria andStudentEmailBetween(String value1, String value2) {
            addCriterion("student_email between", value1, value2, "studentEmail");
            return (Criteria) this;
        }

        public Criteria andStudentEmailNotBetween(String value1, String value2) {
            addCriterion("student_email not between", value1, value2, "studentEmail");
            return (Criteria) this;
        }

        public Criteria andStudentRemarkIsNull() {
            addCriterion("student_remark is null");
            return (Criteria) this;
        }

        public Criteria andStudentRemarkIsNotNull() {
            addCriterion("student_remark is not null");
            return (Criteria) this;
        }

        public Criteria andStudentRemarkEqualTo(String value) {
            addCriterion("student_remark =", value, "studentRemark");
            return (Criteria) this;
        }

        public Criteria andStudentRemarkNotEqualTo(String value) {
            addCriterion("student_remark <>", value, "studentRemark");
            return (Criteria) this;
        }

        public Criteria andStudentRemarkGreaterThan(String value) {
            addCriterion("student_remark >", value, "studentRemark");
            return (Criteria) this;
        }

        public Criteria andStudentRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("student_remark >=", value, "studentRemark");
            return (Criteria) this;
        }

        public Criteria andStudentRemarkLessThan(String value) {
            addCriterion("student_remark <", value, "studentRemark");
            return (Criteria) this;
        }

        public Criteria andStudentRemarkLessThanOrEqualTo(String value) {
            addCriterion("student_remark <=", value, "studentRemark");
            return (Criteria) this;
        }

        public Criteria andStudentRemarkLike(String value) {
            addCriterion("student_remark like", value, "studentRemark");
            return (Criteria) this;
        }

        public Criteria andStudentRemarkNotLike(String value) {
            addCriterion("student_remark not like", value, "studentRemark");
            return (Criteria) this;
        }

        public Criteria andStudentRemarkIn(List<String> values) {
            addCriterion("student_remark in", values, "studentRemark");
            return (Criteria) this;
        }

        public Criteria andStudentRemarkNotIn(List<String> values) {
            addCriterion("student_remark not in", values, "studentRemark");
            return (Criteria) this;
        }

        public Criteria andStudentRemarkBetween(String value1, String value2) {
            addCriterion("student_remark between", value1, value2, "studentRemark");
            return (Criteria) this;
        }

        public Criteria andStudentRemarkNotBetween(String value1, String value2) {
            addCriterion("student_remark not between", value1, value2, "studentRemark");
            return (Criteria) this;
        }

        public Criteria andStudentPhotoIsNull() {
            addCriterion("student_photo is null");
            return (Criteria) this;
        }

        public Criteria andStudentPhotoIsNotNull() {
            addCriterion("student_photo is not null");
            return (Criteria) this;
        }

        public Criteria andStudentPhotoEqualTo(String value) {
            addCriterion("student_photo =", value, "studentPhoto");
            return (Criteria) this;
        }

        public Criteria andStudentPhotoNotEqualTo(String value) {
            addCriterion("student_photo <>", value, "studentPhoto");
            return (Criteria) this;
        }

        public Criteria andStudentPhotoGreaterThan(String value) {
            addCriterion("student_photo >", value, "studentPhoto");
            return (Criteria) this;
        }

        public Criteria andStudentPhotoGreaterThanOrEqualTo(String value) {
            addCriterion("student_photo >=", value, "studentPhoto");
            return (Criteria) this;
        }

        public Criteria andStudentPhotoLessThan(String value) {
            addCriterion("student_photo <", value, "studentPhoto");
            return (Criteria) this;
        }

        public Criteria andStudentPhotoLessThanOrEqualTo(String value) {
            addCriterion("student_photo <=", value, "studentPhoto");
            return (Criteria) this;
        }

        public Criteria andStudentPhotoLike(String value) {
            addCriterion("student_photo like", value, "studentPhoto");
            return (Criteria) this;
        }

        public Criteria andStudentPhotoNotLike(String value) {
            addCriterion("student_photo not like", value, "studentPhoto");
            return (Criteria) this;
        }

        public Criteria andStudentPhotoIn(List<String> values) {
            addCriterion("student_photo in", values, "studentPhoto");
            return (Criteria) this;
        }

        public Criteria andStudentPhotoNotIn(List<String> values) {
            addCriterion("student_photo not in", values, "studentPhoto");
            return (Criteria) this;
        }

        public Criteria andStudentPhotoBetween(String value1, String value2) {
            addCriterion("student_photo between", value1, value2, "studentPhoto");
            return (Criteria) this;
        }

        public Criteria andStudentPhotoNotBetween(String value1, String value2) {
            addCriterion("student_photo not between", value1, value2, "studentPhoto");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table student_info
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table student_info
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}