package com.education.system.entity;

import java.io.Serializable;
import java.util.Date;

public class StudentInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.student_Id
     *
     * @mbggenerated
     */
    private Integer studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.student_Name
     *
     * @mbggenerated
     */
    private String studentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.student_Gender
     *
     * @mbggenerated
     */
    private String studentGender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.student_Racial
     *
     * @mbggenerated
     */
    private String studentRacial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.student_Birthday
     *
     * @mbggenerated
     */
    private Date studentBirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.student_Join_Time
     *
     * @mbggenerated
     */
    private Date studentJoinTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.student_Major
     *
     * @mbggenerated
     */
    private String studentMajor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.student_Class
     *
     * @mbggenerated
     */
    private String studentClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.student_First_Parent
     *
     * @mbggenerated
     */
    private String studentFirstParent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.student_First_Parent_Work
     *
     * @mbggenerated
     */
    private String studentFirstParentWork;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.student_Second_Parent
     *
     * @mbggenerated
     */
    private String studentSecondParent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.studentSecond_Parent_Work
     *
     * @mbggenerated
     */
    private String studentsecondParentWork;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.student_Native_Place
     *
     * @mbggenerated
     */
    private String studentNativePlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.student_Address
     *
     * @mbggenerated
     */
    private String studentAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.student_Phone
     *
     * @mbggenerated
     */
    private Integer studentPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.student_Cell_Phone
     *
     * @mbggenerated
     */
    private Integer studentCellPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.student_Email
     *
     * @mbggenerated
     */
    private String studentEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.student_Photo
     *
     * @mbggenerated
     */
    private String studentPhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.student_Id
     *
     * @return the value of student_info.student_Id
     *
     * @mbggenerated
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.student_Id
     *
     * @param studentId the value for student_info.student_Id
     *
     * @mbggenerated
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.student_Name
     *
     * @return the value of student_info.student_Name
     *
     * @mbggenerated
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.student_Name
     *
     * @param studentName the value for student_info.student_Name
     *
     * @mbggenerated
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.student_Gender
     *
     * @return the value of student_info.student_Gender
     *
     * @mbggenerated
     */
    public String getStudentGender() {
        return studentGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.student_Gender
     *
     * @param studentGender the value for student_info.student_Gender
     *
     * @mbggenerated
     */
    public void setStudentGender(String studentGender) {
        this.studentGender = studentGender == null ? null : studentGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.student_Racial
     *
     * @return the value of student_info.student_Racial
     *
     * @mbggenerated
     */
    public String getStudentRacial() {
        return studentRacial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.student_Racial
     *
     * @param studentRacial the value for student_info.student_Racial
     *
     * @mbggenerated
     */
    public void setStudentRacial(String studentRacial) {
        this.studentRacial = studentRacial == null ? null : studentRacial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.student_Birthday
     *
     * @return the value of student_info.student_Birthday
     *
     * @mbggenerated
     */
    public Date getStudentBirthday() {
        return studentBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.student_Birthday
     *
     * @param studentBirthday the value for student_info.student_Birthday
     *
     * @mbggenerated
     */
    public void setStudentBirthday(Date studentBirthday) {
        this.studentBirthday = studentBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.student_Join_Time
     *
     * @return the value of student_info.student_Join_Time
     *
     * @mbggenerated
     */
    public Date getStudentJoinTime() {
        return studentJoinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.student_Join_Time
     *
     * @param studentJoinTime the value for student_info.student_Join_Time
     *
     * @mbggenerated
     */
    public void setStudentJoinTime(Date studentJoinTime) {
        this.studentJoinTime = studentJoinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.student_Major
     *
     * @return the value of student_info.student_Major
     *
     * @mbggenerated
     */
    public String getStudentMajor() {
        return studentMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.student_Major
     *
     * @param studentMajor the value for student_info.student_Major
     *
     * @mbggenerated
     */
    public void setStudentMajor(String studentMajor) {
        this.studentMajor = studentMajor == null ? null : studentMajor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.student_Class
     *
     * @return the value of student_info.student_Class
     *
     * @mbggenerated
     */
    public String getStudentClass() {
        return studentClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.student_Class
     *
     * @param studentClass the value for student_info.student_Class
     *
     * @mbggenerated
     */
    public void setStudentClass(String studentClass) {
        this.studentClass = studentClass == null ? null : studentClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.student_First_Parent
     *
     * @return the value of student_info.student_First_Parent
     *
     * @mbggenerated
     */
    public String getStudentFirstParent() {
        return studentFirstParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.student_First_Parent
     *
     * @param studentFirstParent the value for student_info.student_First_Parent
     *
     * @mbggenerated
     */
    public void setStudentFirstParent(String studentFirstParent) {
        this.studentFirstParent = studentFirstParent == null ? null : studentFirstParent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.student_First_Parent_Work
     *
     * @return the value of student_info.student_First_Parent_Work
     *
     * @mbggenerated
     */
    public String getStudentFirstParentWork() {
        return studentFirstParentWork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.student_First_Parent_Work
     *
     * @param studentFirstParentWork the value for student_info.student_First_Parent_Work
     *
     * @mbggenerated
     */
    public void setStudentFirstParentWork(String studentFirstParentWork) {
        this.studentFirstParentWork = studentFirstParentWork == null ? null : studentFirstParentWork.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.student_Second_Parent
     *
     * @return the value of student_info.student_Second_Parent
     *
     * @mbggenerated
     */
    public String getStudentSecondParent() {
        return studentSecondParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.student_Second_Parent
     *
     * @param studentSecondParent the value for student_info.student_Second_Parent
     *
     * @mbggenerated
     */
    public void setStudentSecondParent(String studentSecondParent) {
        this.studentSecondParent = studentSecondParent == null ? null : studentSecondParent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.studentSecond_Parent_Work
     *
     * @return the value of student_info.studentSecond_Parent_Work
     *
     * @mbggenerated
     */
    public String getStudentsecondParentWork() {
        return studentsecondParentWork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.studentSecond_Parent_Work
     *
     * @param studentsecondParentWork the value for student_info.studentSecond_Parent_Work
     *
     * @mbggenerated
     */
    public void setStudentsecondParentWork(String studentsecondParentWork) {
        this.studentsecondParentWork = studentsecondParentWork == null ? null : studentsecondParentWork.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.student_Native_Place
     *
     * @return the value of student_info.student_Native_Place
     *
     * @mbggenerated
     */
    public String getStudentNativePlace() {
        return studentNativePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.student_Native_Place
     *
     * @param studentNativePlace the value for student_info.student_Native_Place
     *
     * @mbggenerated
     */
    public void setStudentNativePlace(String studentNativePlace) {
        this.studentNativePlace = studentNativePlace == null ? null : studentNativePlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.student_Address
     *
     * @return the value of student_info.student_Address
     *
     * @mbggenerated
     */
    public String getStudentAddress() {
        return studentAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.student_Address
     *
     * @param studentAddress the value for student_info.student_Address
     *
     * @mbggenerated
     */
    public void setStudentAddress(String studentAddress) {
        this.studentAddress = studentAddress == null ? null : studentAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.student_Phone
     *
     * @return the value of student_info.student_Phone
     *
     * @mbggenerated
     */
    public Integer getStudentPhone() {
        return studentPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.student_Phone
     *
     * @param studentPhone the value for student_info.student_Phone
     *
     * @mbggenerated
     */
    public void setStudentPhone(Integer studentPhone) {
        this.studentPhone = studentPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.student_Cell_Phone
     *
     * @return the value of student_info.student_Cell_Phone
     *
     * @mbggenerated
     */
    public Integer getStudentCellPhone() {
        return studentCellPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.student_Cell_Phone
     *
     * @param studentCellPhone the value for student_info.student_Cell_Phone
     *
     * @mbggenerated
     */
    public void setStudentCellPhone(Integer studentCellPhone) {
        this.studentCellPhone = studentCellPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.student_Email
     *
     * @return the value of student_info.student_Email
     *
     * @mbggenerated
     */
    public String getStudentEmail() {
        return studentEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.student_Email
     *
     * @param studentEmail the value for student_info.student_Email
     *
     * @mbggenerated
     */
    public void setStudentEmail(String studentEmail) {
        this.studentEmail = studentEmail == null ? null : studentEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.student_Photo
     *
     * @return the value of student_info.student_Photo
     *
     * @mbggenerated
     */
    public String getStudentPhoto() {
        return studentPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.student_Photo
     *
     * @param studentPhoto the value for student_info.student_Photo
     *
     * @mbggenerated
     */
    public void setStudentPhoto(String studentPhoto) {
        this.studentPhoto = studentPhoto == null ? null : studentPhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", studentId=").append(studentId);
        sb.append(", studentName=").append(studentName);
        sb.append(", studentGender=").append(studentGender);
        sb.append(", studentRacial=").append(studentRacial);
        sb.append(", studentBirthday=").append(studentBirthday);
        sb.append(", studentJoinTime=").append(studentJoinTime);
        sb.append(", studentMajor=").append(studentMajor);
        sb.append(", studentClass=").append(studentClass);
        sb.append(", studentFirstParent=").append(studentFirstParent);
        sb.append(", studentFirstParentWork=").append(studentFirstParentWork);
        sb.append(", studentSecondParent=").append(studentSecondParent);
        sb.append(", studentsecondParentWork=").append(studentsecondParentWork);
        sb.append(", studentNativePlace=").append(studentNativePlace);
        sb.append(", studentAddress=").append(studentAddress);
        sb.append(", studentPhone=").append(studentPhone);
        sb.append(", studentCellPhone=").append(studentCellPhone);
        sb.append(", studentEmail=").append(studentEmail);
        sb.append(", studentPhoto=").append(studentPhoto);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}