package com.education.system.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class StudentTranscript implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_transcript.student_id
     *
     * @mbggenerated
     */
    private Integer studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_transcript.student_name
     *
     * @mbggenerated
     */
    private String studentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_transcript.student_class
     *
     * @mbggenerated
     */
    private String studentClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_transcript.teacher_id
     *
     * @mbggenerated
     */
    private Integer teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_transcript.teacher_name
     *
     * @mbggenerated
     */
    private String teacherName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_transcript.course_id
     *
     * @mbggenerated
     */
    private Integer courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_transcript.course_name
     *
     * @mbggenerated
     */
    private String courseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_transcript.course_grade
     *
     * @mbggenerated
     */
    private String courseGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_transcript.course_score
     *
     * @mbggenerated
     */
    private BigDecimal courseScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_transcript.course_credit
     *
     * @mbggenerated
     */
    private BigDecimal courseCredit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student_transcript
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_transcript.student_id
     *
     * @return the value of student_transcript.student_id
     *
     * @mbggenerated
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_transcript.student_id
     *
     * @param studentId the value for student_transcript.student_id
     *
     * @mbggenerated
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_transcript.student_name
     *
     * @return the value of student_transcript.student_name
     *
     * @mbggenerated
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_transcript.student_name
     *
     * @param studentName the value for student_transcript.student_name
     *
     * @mbggenerated
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_transcript.student_class
     *
     * @return the value of student_transcript.student_class
     *
     * @mbggenerated
     */
    public String getStudentClass() {
        return studentClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_transcript.student_class
     *
     * @param studentClass the value for student_transcript.student_class
     *
     * @mbggenerated
     */
    public void setStudentClass(String studentClass) {
        this.studentClass = studentClass == null ? null : studentClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_transcript.teacher_id
     *
     * @return the value of student_transcript.teacher_id
     *
     * @mbggenerated
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_transcript.teacher_id
     *
     * @param teacherId the value for student_transcript.teacher_id
     *
     * @mbggenerated
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_transcript.teacher_name
     *
     * @return the value of student_transcript.teacher_name
     *
     * @mbggenerated
     */
    public String getTeacherName() {
        return teacherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_transcript.teacher_name
     *
     * @param teacherName the value for student_transcript.teacher_name
     *
     * @mbggenerated
     */
    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName == null ? null : teacherName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_transcript.course_id
     *
     * @return the value of student_transcript.course_id
     *
     * @mbggenerated
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_transcript.course_id
     *
     * @param courseId the value for student_transcript.course_id
     *
     * @mbggenerated
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_transcript.course_name
     *
     * @return the value of student_transcript.course_name
     *
     * @mbggenerated
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_transcript.course_name
     *
     * @param courseName the value for student_transcript.course_name
     *
     * @mbggenerated
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_transcript.course_grade
     *
     * @return the value of student_transcript.course_grade
     *
     * @mbggenerated
     */
    public String getCourseGrade() {
        return courseGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_transcript.course_grade
     *
     * @param courseGrade the value for student_transcript.course_grade
     *
     * @mbggenerated
     */
    public void setCourseGrade(String courseGrade) {
        this.courseGrade = courseGrade == null ? null : courseGrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_transcript.course_score
     *
     * @return the value of student_transcript.course_score
     *
     * @mbggenerated
     */
    public BigDecimal getCourseScore() {
        return courseScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_transcript.course_score
     *
     * @param courseScore the value for student_transcript.course_score
     *
     * @mbggenerated
     */
    public void setCourseScore(BigDecimal courseScore) {
        this.courseScore = courseScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_transcript.course_credit
     *
     * @return the value of student_transcript.course_credit
     *
     * @mbggenerated
     */
    public BigDecimal getCourseCredit() {
        return courseCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_transcript.course_credit
     *
     * @param courseCredit the value for student_transcript.course_credit
     *
     * @mbggenerated
     */
    public void setCourseCredit(BigDecimal courseCredit) {
        this.courseCredit = courseCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_transcript
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", studentId=").append(studentId);
        sb.append(", studentName=").append(studentName);
        sb.append(", studentClass=").append(studentClass);
        sb.append(", teacherId=").append(teacherId);
        sb.append(", teacherName=").append(teacherName);
        sb.append(", courseId=").append(courseId);
        sb.append(", courseName=").append(courseName);
        sb.append(", courseGrade=").append(courseGrade);
        sb.append(", courseScore=").append(courseScore);
        sb.append(", courseCredit=").append(courseCredit);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}