package com.education.system.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TeacherInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table teacher_info
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table teacher_info
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table teacher_info
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_info
     *
     * @mbggenerated
     */
    public TeacherInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_info
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_info
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_info
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_info
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_info
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_info
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_info
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_info
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_info
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_info
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table teacher_info
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andTeacherIdIsNull() {
            addCriterion("teacher_Id is null");
            return (Criteria) this;
        }

        public Criteria andTeacherIdIsNotNull() {
            addCriterion("teacher_Id is not null");
            return (Criteria) this;
        }

        public Criteria andTeacherIdEqualTo(Integer value) {
            addCriterion("teacher_Id =", value, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdNotEqualTo(Integer value) {
            addCriterion("teacher_Id <>", value, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdGreaterThan(Integer value) {
            addCriterion("teacher_Id >", value, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("teacher_Id >=", value, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdLessThan(Integer value) {
            addCriterion("teacher_Id <", value, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdLessThanOrEqualTo(Integer value) {
            addCriterion("teacher_Id <=", value, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdIn(List<Integer> values) {
            addCriterion("teacher_Id in", values, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdNotIn(List<Integer> values) {
            addCriterion("teacher_Id not in", values, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdBetween(Integer value1, Integer value2) {
            addCriterion("teacher_Id between", value1, value2, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdNotBetween(Integer value1, Integer value2) {
            addCriterion("teacher_Id not between", value1, value2, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherNameIsNull() {
            addCriterion("teacher_Name is null");
            return (Criteria) this;
        }

        public Criteria andTeacherNameIsNotNull() {
            addCriterion("teacher_Name is not null");
            return (Criteria) this;
        }

        public Criteria andTeacherNameEqualTo(String value) {
            addCriterion("teacher_Name =", value, "teacherName");
            return (Criteria) this;
        }

        public Criteria andTeacherNameNotEqualTo(String value) {
            addCriterion("teacher_Name <>", value, "teacherName");
            return (Criteria) this;
        }

        public Criteria andTeacherNameGreaterThan(String value) {
            addCriterion("teacher_Name >", value, "teacherName");
            return (Criteria) this;
        }

        public Criteria andTeacherNameGreaterThanOrEqualTo(String value) {
            addCriterion("teacher_Name >=", value, "teacherName");
            return (Criteria) this;
        }

        public Criteria andTeacherNameLessThan(String value) {
            addCriterion("teacher_Name <", value, "teacherName");
            return (Criteria) this;
        }

        public Criteria andTeacherNameLessThanOrEqualTo(String value) {
            addCriterion("teacher_Name <=", value, "teacherName");
            return (Criteria) this;
        }

        public Criteria andTeacherNameLike(String value) {
            addCriterion("teacher_Name like", value, "teacherName");
            return (Criteria) this;
        }

        public Criteria andTeacherNameNotLike(String value) {
            addCriterion("teacher_Name not like", value, "teacherName");
            return (Criteria) this;
        }

        public Criteria andTeacherNameIn(List<String> values) {
            addCriterion("teacher_Name in", values, "teacherName");
            return (Criteria) this;
        }

        public Criteria andTeacherNameNotIn(List<String> values) {
            addCriterion("teacher_Name not in", values, "teacherName");
            return (Criteria) this;
        }

        public Criteria andTeacherNameBetween(String value1, String value2) {
            addCriterion("teacher_Name between", value1, value2, "teacherName");
            return (Criteria) this;
        }

        public Criteria andTeacherNameNotBetween(String value1, String value2) {
            addCriterion("teacher_Name not between", value1, value2, "teacherName");
            return (Criteria) this;
        }

        public Criteria andTeacherGenderIsNull() {
            addCriterion("teacher_Gender is null");
            return (Criteria) this;
        }

        public Criteria andTeacherGenderIsNotNull() {
            addCriterion("teacher_Gender is not null");
            return (Criteria) this;
        }

        public Criteria andTeacherGenderEqualTo(String value) {
            addCriterion("teacher_Gender =", value, "teacherGender");
            return (Criteria) this;
        }

        public Criteria andTeacherGenderNotEqualTo(String value) {
            addCriterion("teacher_Gender <>", value, "teacherGender");
            return (Criteria) this;
        }

        public Criteria andTeacherGenderGreaterThan(String value) {
            addCriterion("teacher_Gender >", value, "teacherGender");
            return (Criteria) this;
        }

        public Criteria andTeacherGenderGreaterThanOrEqualTo(String value) {
            addCriterion("teacher_Gender >=", value, "teacherGender");
            return (Criteria) this;
        }

        public Criteria andTeacherGenderLessThan(String value) {
            addCriterion("teacher_Gender <", value, "teacherGender");
            return (Criteria) this;
        }

        public Criteria andTeacherGenderLessThanOrEqualTo(String value) {
            addCriterion("teacher_Gender <=", value, "teacherGender");
            return (Criteria) this;
        }

        public Criteria andTeacherGenderLike(String value) {
            addCriterion("teacher_Gender like", value, "teacherGender");
            return (Criteria) this;
        }

        public Criteria andTeacherGenderNotLike(String value) {
            addCriterion("teacher_Gender not like", value, "teacherGender");
            return (Criteria) this;
        }

        public Criteria andTeacherGenderIn(List<String> values) {
            addCriterion("teacher_Gender in", values, "teacherGender");
            return (Criteria) this;
        }

        public Criteria andTeacherGenderNotIn(List<String> values) {
            addCriterion("teacher_Gender not in", values, "teacherGender");
            return (Criteria) this;
        }

        public Criteria andTeacherGenderBetween(String value1, String value2) {
            addCriterion("teacher_Gender between", value1, value2, "teacherGender");
            return (Criteria) this;
        }

        public Criteria andTeacherGenderNotBetween(String value1, String value2) {
            addCriterion("teacher_Gender not between", value1, value2, "teacherGender");
            return (Criteria) this;
        }

        public Criteria andTeacherBirthdayIsNull() {
            addCriterion("teacher_Birthday is null");
            return (Criteria) this;
        }

        public Criteria andTeacherBirthdayIsNotNull() {
            addCriterion("teacher_Birthday is not null");
            return (Criteria) this;
        }

        public Criteria andTeacherBirthdayEqualTo(Date value) {
            addCriterionForJDBCDate("teacher_Birthday =", value, "teacherBirthday");
            return (Criteria) this;
        }

        public Criteria andTeacherBirthdayNotEqualTo(Date value) {
            addCriterionForJDBCDate("teacher_Birthday <>", value, "teacherBirthday");
            return (Criteria) this;
        }

        public Criteria andTeacherBirthdayGreaterThan(Date value) {
            addCriterionForJDBCDate("teacher_Birthday >", value, "teacherBirthday");
            return (Criteria) this;
        }

        public Criteria andTeacherBirthdayGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("teacher_Birthday >=", value, "teacherBirthday");
            return (Criteria) this;
        }

        public Criteria andTeacherBirthdayLessThan(Date value) {
            addCriterionForJDBCDate("teacher_Birthday <", value, "teacherBirthday");
            return (Criteria) this;
        }

        public Criteria andTeacherBirthdayLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("teacher_Birthday <=", value, "teacherBirthday");
            return (Criteria) this;
        }

        public Criteria andTeacherBirthdayIn(List<Date> values) {
            addCriterionForJDBCDate("teacher_Birthday in", values, "teacherBirthday");
            return (Criteria) this;
        }

        public Criteria andTeacherBirthdayNotIn(List<Date> values) {
            addCriterionForJDBCDate("teacher_Birthday not in", values, "teacherBirthday");
            return (Criteria) this;
        }

        public Criteria andTeacherBirthdayBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("teacher_Birthday between", value1, value2, "teacherBirthday");
            return (Criteria) this;
        }

        public Criteria andTeacherBirthdayNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("teacher_Birthday not between", value1, value2, "teacherBirthday");
            return (Criteria) this;
        }

        public Criteria andTeacherRacialIsNull() {
            addCriterion("teacher_Racial is null");
            return (Criteria) this;
        }

        public Criteria andTeacherRacialIsNotNull() {
            addCriterion("teacher_Racial is not null");
            return (Criteria) this;
        }

        public Criteria andTeacherRacialEqualTo(String value) {
            addCriterion("teacher_Racial =", value, "teacherRacial");
            return (Criteria) this;
        }

        public Criteria andTeacherRacialNotEqualTo(String value) {
            addCriterion("teacher_Racial <>", value, "teacherRacial");
            return (Criteria) this;
        }

        public Criteria andTeacherRacialGreaterThan(String value) {
            addCriterion("teacher_Racial >", value, "teacherRacial");
            return (Criteria) this;
        }

        public Criteria andTeacherRacialGreaterThanOrEqualTo(String value) {
            addCriterion("teacher_Racial >=", value, "teacherRacial");
            return (Criteria) this;
        }

        public Criteria andTeacherRacialLessThan(String value) {
            addCriterion("teacher_Racial <", value, "teacherRacial");
            return (Criteria) this;
        }

        public Criteria andTeacherRacialLessThanOrEqualTo(String value) {
            addCriterion("teacher_Racial <=", value, "teacherRacial");
            return (Criteria) this;
        }

        public Criteria andTeacherRacialLike(String value) {
            addCriterion("teacher_Racial like", value, "teacherRacial");
            return (Criteria) this;
        }

        public Criteria andTeacherRacialNotLike(String value) {
            addCriterion("teacher_Racial not like", value, "teacherRacial");
            return (Criteria) this;
        }

        public Criteria andTeacherRacialIn(List<String> values) {
            addCriterion("teacher_Racial in", values, "teacherRacial");
            return (Criteria) this;
        }

        public Criteria andTeacherRacialNotIn(List<String> values) {
            addCriterion("teacher_Racial not in", values, "teacherRacial");
            return (Criteria) this;
        }

        public Criteria andTeacherRacialBetween(String value1, String value2) {
            addCriterion("teacher_Racial between", value1, value2, "teacherRacial");
            return (Criteria) this;
        }

        public Criteria andTeacherRacialNotBetween(String value1, String value2) {
            addCriterion("teacher_Racial not between", value1, value2, "teacherRacial");
            return (Criteria) this;
        }

        public Criteria andTeacherGraduateSchoolIsNull() {
            addCriterion("teacher_Graduate_School is null");
            return (Criteria) this;
        }

        public Criteria andTeacherGraduateSchoolIsNotNull() {
            addCriterion("teacher_Graduate_School is not null");
            return (Criteria) this;
        }

        public Criteria andTeacherGraduateSchoolEqualTo(String value) {
            addCriterion("teacher_Graduate_School =", value, "teacherGraduateSchool");
            return (Criteria) this;
        }

        public Criteria andTeacherGraduateSchoolNotEqualTo(String value) {
            addCriterion("teacher_Graduate_School <>", value, "teacherGraduateSchool");
            return (Criteria) this;
        }

        public Criteria andTeacherGraduateSchoolGreaterThan(String value) {
            addCriterion("teacher_Graduate_School >", value, "teacherGraduateSchool");
            return (Criteria) this;
        }

        public Criteria andTeacherGraduateSchoolGreaterThanOrEqualTo(String value) {
            addCriterion("teacher_Graduate_School >=", value, "teacherGraduateSchool");
            return (Criteria) this;
        }

        public Criteria andTeacherGraduateSchoolLessThan(String value) {
            addCriterion("teacher_Graduate_School <", value, "teacherGraduateSchool");
            return (Criteria) this;
        }

        public Criteria andTeacherGraduateSchoolLessThanOrEqualTo(String value) {
            addCriterion("teacher_Graduate_School <=", value, "teacherGraduateSchool");
            return (Criteria) this;
        }

        public Criteria andTeacherGraduateSchoolLike(String value) {
            addCriterion("teacher_Graduate_School like", value, "teacherGraduateSchool");
            return (Criteria) this;
        }

        public Criteria andTeacherGraduateSchoolNotLike(String value) {
            addCriterion("teacher_Graduate_School not like", value, "teacherGraduateSchool");
            return (Criteria) this;
        }

        public Criteria andTeacherGraduateSchoolIn(List<String> values) {
            addCriterion("teacher_Graduate_School in", values, "teacherGraduateSchool");
            return (Criteria) this;
        }

        public Criteria andTeacherGraduateSchoolNotIn(List<String> values) {
            addCriterion("teacher_Graduate_School not in", values, "teacherGraduateSchool");
            return (Criteria) this;
        }

        public Criteria andTeacherGraduateSchoolBetween(String value1, String value2) {
            addCriterion("teacher_Graduate_School between", value1, value2, "teacherGraduateSchool");
            return (Criteria) this;
        }

        public Criteria andTeacherGraduateSchoolNotBetween(String value1, String value2) {
            addCriterion("teacher_Graduate_School not between", value1, value2, "teacherGraduateSchool");
            return (Criteria) this;
        }

        public Criteria andTeacherPostIsNull() {
            addCriterion("teacher_Post is null");
            return (Criteria) this;
        }

        public Criteria andTeacherPostIsNotNull() {
            addCriterion("teacher_Post is not null");
            return (Criteria) this;
        }

        public Criteria andTeacherPostEqualTo(String value) {
            addCriterion("teacher_Post =", value, "teacherPost");
            return (Criteria) this;
        }

        public Criteria andTeacherPostNotEqualTo(String value) {
            addCriterion("teacher_Post <>", value, "teacherPost");
            return (Criteria) this;
        }

        public Criteria andTeacherPostGreaterThan(String value) {
            addCriterion("teacher_Post >", value, "teacherPost");
            return (Criteria) this;
        }

        public Criteria andTeacherPostGreaterThanOrEqualTo(String value) {
            addCriterion("teacher_Post >=", value, "teacherPost");
            return (Criteria) this;
        }

        public Criteria andTeacherPostLessThan(String value) {
            addCriterion("teacher_Post <", value, "teacherPost");
            return (Criteria) this;
        }

        public Criteria andTeacherPostLessThanOrEqualTo(String value) {
            addCriterion("teacher_Post <=", value, "teacherPost");
            return (Criteria) this;
        }

        public Criteria andTeacherPostLike(String value) {
            addCriterion("teacher_Post like", value, "teacherPost");
            return (Criteria) this;
        }

        public Criteria andTeacherPostNotLike(String value) {
            addCriterion("teacher_Post not like", value, "teacherPost");
            return (Criteria) this;
        }

        public Criteria andTeacherPostIn(List<String> values) {
            addCriterion("teacher_Post in", values, "teacherPost");
            return (Criteria) this;
        }

        public Criteria andTeacherPostNotIn(List<String> values) {
            addCriterion("teacher_Post not in", values, "teacherPost");
            return (Criteria) this;
        }

        public Criteria andTeacherPostBetween(String value1, String value2) {
            addCriterion("teacher_Post between", value1, value2, "teacherPost");
            return (Criteria) this;
        }

        public Criteria andTeacherPostNotBetween(String value1, String value2) {
            addCriterion("teacher_Post not between", value1, value2, "teacherPost");
            return (Criteria) this;
        }

        public Criteria andTeacherNativePlaceIsNull() {
            addCriterion("teacher_Native_Place is null");
            return (Criteria) this;
        }

        public Criteria andTeacherNativePlaceIsNotNull() {
            addCriterion("teacher_Native_Place is not null");
            return (Criteria) this;
        }

        public Criteria andTeacherNativePlaceEqualTo(String value) {
            addCriterion("teacher_Native_Place =", value, "teacherNativePlace");
            return (Criteria) this;
        }

        public Criteria andTeacherNativePlaceNotEqualTo(String value) {
            addCriterion("teacher_Native_Place <>", value, "teacherNativePlace");
            return (Criteria) this;
        }

        public Criteria andTeacherNativePlaceGreaterThan(String value) {
            addCriterion("teacher_Native_Place >", value, "teacherNativePlace");
            return (Criteria) this;
        }

        public Criteria andTeacherNativePlaceGreaterThanOrEqualTo(String value) {
            addCriterion("teacher_Native_Place >=", value, "teacherNativePlace");
            return (Criteria) this;
        }

        public Criteria andTeacherNativePlaceLessThan(String value) {
            addCriterion("teacher_Native_Place <", value, "teacherNativePlace");
            return (Criteria) this;
        }

        public Criteria andTeacherNativePlaceLessThanOrEqualTo(String value) {
            addCriterion("teacher_Native_Place <=", value, "teacherNativePlace");
            return (Criteria) this;
        }

        public Criteria andTeacherNativePlaceLike(String value) {
            addCriterion("teacher_Native_Place like", value, "teacherNativePlace");
            return (Criteria) this;
        }

        public Criteria andTeacherNativePlaceNotLike(String value) {
            addCriterion("teacher_Native_Place not like", value, "teacherNativePlace");
            return (Criteria) this;
        }

        public Criteria andTeacherNativePlaceIn(List<String> values) {
            addCriterion("teacher_Native_Place in", values, "teacherNativePlace");
            return (Criteria) this;
        }

        public Criteria andTeacherNativePlaceNotIn(List<String> values) {
            addCriterion("teacher_Native_Place not in", values, "teacherNativePlace");
            return (Criteria) this;
        }

        public Criteria andTeacherNativePlaceBetween(String value1, String value2) {
            addCriterion("teacher_Native_Place between", value1, value2, "teacherNativePlace");
            return (Criteria) this;
        }

        public Criteria andTeacherNativePlaceNotBetween(String value1, String value2) {
            addCriterion("teacher_Native_Place not between", value1, value2, "teacherNativePlace");
            return (Criteria) this;
        }

        public Criteria andTeacherAddressIsNull() {
            addCriterion("teacher_Address is null");
            return (Criteria) this;
        }

        public Criteria andTeacherAddressIsNotNull() {
            addCriterion("teacher_Address is not null");
            return (Criteria) this;
        }

        public Criteria andTeacherAddressEqualTo(String value) {
            addCriterion("teacher_Address =", value, "teacherAddress");
            return (Criteria) this;
        }

        public Criteria andTeacherAddressNotEqualTo(String value) {
            addCriterion("teacher_Address <>", value, "teacherAddress");
            return (Criteria) this;
        }

        public Criteria andTeacherAddressGreaterThan(String value) {
            addCriterion("teacher_Address >", value, "teacherAddress");
            return (Criteria) this;
        }

        public Criteria andTeacherAddressGreaterThanOrEqualTo(String value) {
            addCriterion("teacher_Address >=", value, "teacherAddress");
            return (Criteria) this;
        }

        public Criteria andTeacherAddressLessThan(String value) {
            addCriterion("teacher_Address <", value, "teacherAddress");
            return (Criteria) this;
        }

        public Criteria andTeacherAddressLessThanOrEqualTo(String value) {
            addCriterion("teacher_Address <=", value, "teacherAddress");
            return (Criteria) this;
        }

        public Criteria andTeacherAddressLike(String value) {
            addCriterion("teacher_Address like", value, "teacherAddress");
            return (Criteria) this;
        }

        public Criteria andTeacherAddressNotLike(String value) {
            addCriterion("teacher_Address not like", value, "teacherAddress");
            return (Criteria) this;
        }

        public Criteria andTeacherAddressIn(List<String> values) {
            addCriterion("teacher_Address in", values, "teacherAddress");
            return (Criteria) this;
        }

        public Criteria andTeacherAddressNotIn(List<String> values) {
            addCriterion("teacher_Address not in", values, "teacherAddress");
            return (Criteria) this;
        }

        public Criteria andTeacherAddressBetween(String value1, String value2) {
            addCriterion("teacher_Address between", value1, value2, "teacherAddress");
            return (Criteria) this;
        }

        public Criteria andTeacherAddressNotBetween(String value1, String value2) {
            addCriterion("teacher_Address not between", value1, value2, "teacherAddress");
            return (Criteria) this;
        }

        public Criteria andTeacherPhoneIsNull() {
            addCriterion("teacher_Phone is null");
            return (Criteria) this;
        }

        public Criteria andTeacherPhoneIsNotNull() {
            addCriterion("teacher_Phone is not null");
            return (Criteria) this;
        }

        public Criteria andTeacherPhoneEqualTo(Integer value) {
            addCriterion("teacher_Phone =", value, "teacherPhone");
            return (Criteria) this;
        }

        public Criteria andTeacherPhoneNotEqualTo(Integer value) {
            addCriterion("teacher_Phone <>", value, "teacherPhone");
            return (Criteria) this;
        }

        public Criteria andTeacherPhoneGreaterThan(Integer value) {
            addCriterion("teacher_Phone >", value, "teacherPhone");
            return (Criteria) this;
        }

        public Criteria andTeacherPhoneGreaterThanOrEqualTo(Integer value) {
            addCriterion("teacher_Phone >=", value, "teacherPhone");
            return (Criteria) this;
        }

        public Criteria andTeacherPhoneLessThan(Integer value) {
            addCriterion("teacher_Phone <", value, "teacherPhone");
            return (Criteria) this;
        }

        public Criteria andTeacherPhoneLessThanOrEqualTo(Integer value) {
            addCriterion("teacher_Phone <=", value, "teacherPhone");
            return (Criteria) this;
        }

        public Criteria andTeacherPhoneIn(List<Integer> values) {
            addCriterion("teacher_Phone in", values, "teacherPhone");
            return (Criteria) this;
        }

        public Criteria andTeacherPhoneNotIn(List<Integer> values) {
            addCriterion("teacher_Phone not in", values, "teacherPhone");
            return (Criteria) this;
        }

        public Criteria andTeacherPhoneBetween(Integer value1, Integer value2) {
            addCriterion("teacher_Phone between", value1, value2, "teacherPhone");
            return (Criteria) this;
        }

        public Criteria andTeacherPhoneNotBetween(Integer value1, Integer value2) {
            addCriterion("teacher_Phone not between", value1, value2, "teacherPhone");
            return (Criteria) this;
        }

        public Criteria andTeacherCellPhoneIsNull() {
            addCriterion("teacher_Cell_Phone is null");
            return (Criteria) this;
        }

        public Criteria andTeacherCellPhoneIsNotNull() {
            addCriterion("teacher_Cell_Phone is not null");
            return (Criteria) this;
        }

        public Criteria andTeacherCellPhoneEqualTo(Integer value) {
            addCriterion("teacher_Cell_Phone =", value, "teacherCellPhone");
            return (Criteria) this;
        }

        public Criteria andTeacherCellPhoneNotEqualTo(Integer value) {
            addCriterion("teacher_Cell_Phone <>", value, "teacherCellPhone");
            return (Criteria) this;
        }

        public Criteria andTeacherCellPhoneGreaterThan(Integer value) {
            addCriterion("teacher_Cell_Phone >", value, "teacherCellPhone");
            return (Criteria) this;
        }

        public Criteria andTeacherCellPhoneGreaterThanOrEqualTo(Integer value) {
            addCriterion("teacher_Cell_Phone >=", value, "teacherCellPhone");
            return (Criteria) this;
        }

        public Criteria andTeacherCellPhoneLessThan(Integer value) {
            addCriterion("teacher_Cell_Phone <", value, "teacherCellPhone");
            return (Criteria) this;
        }

        public Criteria andTeacherCellPhoneLessThanOrEqualTo(Integer value) {
            addCriterion("teacher_Cell_Phone <=", value, "teacherCellPhone");
            return (Criteria) this;
        }

        public Criteria andTeacherCellPhoneIn(List<Integer> values) {
            addCriterion("teacher_Cell_Phone in", values, "teacherCellPhone");
            return (Criteria) this;
        }

        public Criteria andTeacherCellPhoneNotIn(List<Integer> values) {
            addCriterion("teacher_Cell_Phone not in", values, "teacherCellPhone");
            return (Criteria) this;
        }

        public Criteria andTeacherCellPhoneBetween(Integer value1, Integer value2) {
            addCriterion("teacher_Cell_Phone between", value1, value2, "teacherCellPhone");
            return (Criteria) this;
        }

        public Criteria andTeacherCellPhoneNotBetween(Integer value1, Integer value2) {
            addCriterion("teacher_Cell_Phone not between", value1, value2, "teacherCellPhone");
            return (Criteria) this;
        }

        public Criteria andTeacherEmailIsNull() {
            addCriterion("teacher_Email is null");
            return (Criteria) this;
        }

        public Criteria andTeacherEmailIsNotNull() {
            addCriterion("teacher_Email is not null");
            return (Criteria) this;
        }

        public Criteria andTeacherEmailEqualTo(String value) {
            addCriterion("teacher_Email =", value, "teacherEmail");
            return (Criteria) this;
        }

        public Criteria andTeacherEmailNotEqualTo(String value) {
            addCriterion("teacher_Email <>", value, "teacherEmail");
            return (Criteria) this;
        }

        public Criteria andTeacherEmailGreaterThan(String value) {
            addCriterion("teacher_Email >", value, "teacherEmail");
            return (Criteria) this;
        }

        public Criteria andTeacherEmailGreaterThanOrEqualTo(String value) {
            addCriterion("teacher_Email >=", value, "teacherEmail");
            return (Criteria) this;
        }

        public Criteria andTeacherEmailLessThan(String value) {
            addCriterion("teacher_Email <", value, "teacherEmail");
            return (Criteria) this;
        }

        public Criteria andTeacherEmailLessThanOrEqualTo(String value) {
            addCriterion("teacher_Email <=", value, "teacherEmail");
            return (Criteria) this;
        }

        public Criteria andTeacherEmailLike(String value) {
            addCriterion("teacher_Email like", value, "teacherEmail");
            return (Criteria) this;
        }

        public Criteria andTeacherEmailNotLike(String value) {
            addCriterion("teacher_Email not like", value, "teacherEmail");
            return (Criteria) this;
        }

        public Criteria andTeacherEmailIn(List<String> values) {
            addCriterion("teacher_Email in", values, "teacherEmail");
            return (Criteria) this;
        }

        public Criteria andTeacherEmailNotIn(List<String> values) {
            addCriterion("teacher_Email not in", values, "teacherEmail");
            return (Criteria) this;
        }

        public Criteria andTeacherEmailBetween(String value1, String value2) {
            addCriterion("teacher_Email between", value1, value2, "teacherEmail");
            return (Criteria) this;
        }

        public Criteria andTeacherEmailNotBetween(String value1, String value2) {
            addCriterion("teacher_Email not between", value1, value2, "teacherEmail");
            return (Criteria) this;
        }

        public Criteria andTeacherPhotoIsNull() {
            addCriterion("teacher_Photo is null");
            return (Criteria) this;
        }

        public Criteria andTeacherPhotoIsNotNull() {
            addCriterion("teacher_Photo is not null");
            return (Criteria) this;
        }

        public Criteria andTeacherPhotoEqualTo(String value) {
            addCriterion("teacher_Photo =", value, "teacherPhoto");
            return (Criteria) this;
        }

        public Criteria andTeacherPhotoNotEqualTo(String value) {
            addCriterion("teacher_Photo <>", value, "teacherPhoto");
            return (Criteria) this;
        }

        public Criteria andTeacherPhotoGreaterThan(String value) {
            addCriterion("teacher_Photo >", value, "teacherPhoto");
            return (Criteria) this;
        }

        public Criteria andTeacherPhotoGreaterThanOrEqualTo(String value) {
            addCriterion("teacher_Photo >=", value, "teacherPhoto");
            return (Criteria) this;
        }

        public Criteria andTeacherPhotoLessThan(String value) {
            addCriterion("teacher_Photo <", value, "teacherPhoto");
            return (Criteria) this;
        }

        public Criteria andTeacherPhotoLessThanOrEqualTo(String value) {
            addCriterion("teacher_Photo <=", value, "teacherPhoto");
            return (Criteria) this;
        }

        public Criteria andTeacherPhotoLike(String value) {
            addCriterion("teacher_Photo like", value, "teacherPhoto");
            return (Criteria) this;
        }

        public Criteria andTeacherPhotoNotLike(String value) {
            addCriterion("teacher_Photo not like", value, "teacherPhoto");
            return (Criteria) this;
        }

        public Criteria andTeacherPhotoIn(List<String> values) {
            addCriterion("teacher_Photo in", values, "teacherPhoto");
            return (Criteria) this;
        }

        public Criteria andTeacherPhotoNotIn(List<String> values) {
            addCriterion("teacher_Photo not in", values, "teacherPhoto");
            return (Criteria) this;
        }

        public Criteria andTeacherPhotoBetween(String value1, String value2) {
            addCriterion("teacher_Photo between", value1, value2, "teacherPhoto");
            return (Criteria) this;
        }

        public Criteria andTeacherPhotoNotBetween(String value1, String value2) {
            addCriterion("teacher_Photo not between", value1, value2, "teacherPhoto");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table teacher_info
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table teacher_info
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}