package com.education.system.entity;

import java.io.Serializable;
import java.util.Date;

public class TeacherInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.teacher_id
     *
     * @mbggenerated
     */
    private Integer teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.teacher_name
     *
     * @mbggenerated
     */
    private String teacherName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.teacher_gender
     *
     * @mbggenerated
     */
    private String teacherGender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.teacher_birthday
     *
     * @mbggenerated
     */
    private Date teacherBirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.teacher_racial
     *
     * @mbggenerated
     */
    private String teacherRacial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.teacher_native_place
     *
     * @mbggenerated
     */
    private String teacherNativePlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.teacher_marital_status
     *
     * @mbggenerated
     */
    private String teacherMaritalStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.teacher_join_time
     *
     * @mbggenerated
     */
    private Date teacherJoinTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.teacher_education
     *
     * @mbggenerated
     */
    private String teacherEducation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.teacher_graduated_place
     *
     * @mbggenerated
     */
    private String teacherGraduatedPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.teacher_phone
     *
     * @mbggenerated
     */
    private String teacherPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.teacher_cellphone
     *
     * @mbggenerated
     */
    private String teacherCellphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.teacher_eamil
     *
     * @mbggenerated
     */
    private String teacherEamil;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.teacher_position
     *
     * @mbggenerated
     */
    private String teacherPosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.teacher_remark
     *
     * @mbggenerated
     */
    private String teacherRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.teacher_photo
     *
     * @mbggenerated
     */
    private String teacherPhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table teacher_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_info.teacher_id
     *
     * @return the value of teacher_info.teacher_id
     *
     * @mbggenerated
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_info.teacher_id
     *
     * @param teacherId the value for teacher_info.teacher_id
     *
     * @mbggenerated
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_info.teacher_name
     *
     * @return the value of teacher_info.teacher_name
     *
     * @mbggenerated
     */
    public String getTeacherName() {
        return teacherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_info.teacher_name
     *
     * @param teacherName the value for teacher_info.teacher_name
     *
     * @mbggenerated
     */
    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName == null ? null : teacherName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_info.teacher_gender
     *
     * @return the value of teacher_info.teacher_gender
     *
     * @mbggenerated
     */
    public String getTeacherGender() {
        return teacherGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_info.teacher_gender
     *
     * @param teacherGender the value for teacher_info.teacher_gender
     *
     * @mbggenerated
     */
    public void setTeacherGender(String teacherGender) {
        this.teacherGender = teacherGender == null ? null : teacherGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_info.teacher_birthday
     *
     * @return the value of teacher_info.teacher_birthday
     *
     * @mbggenerated
     */
    public Date getTeacherBirthday() {
        return teacherBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_info.teacher_birthday
     *
     * @param teacherBirthday the value for teacher_info.teacher_birthday
     *
     * @mbggenerated
     */
    public void setTeacherBirthday(Date teacherBirthday) {
        this.teacherBirthday = teacherBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_info.teacher_racial
     *
     * @return the value of teacher_info.teacher_racial
     *
     * @mbggenerated
     */
    public String getTeacherRacial() {
        return teacherRacial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_info.teacher_racial
     *
     * @param teacherRacial the value for teacher_info.teacher_racial
     *
     * @mbggenerated
     */
    public void setTeacherRacial(String teacherRacial) {
        this.teacherRacial = teacherRacial == null ? null : teacherRacial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_info.teacher_native_place
     *
     * @return the value of teacher_info.teacher_native_place
     *
     * @mbggenerated
     */
    public String getTeacherNativePlace() {
        return teacherNativePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_info.teacher_native_place
     *
     * @param teacherNativePlace the value for teacher_info.teacher_native_place
     *
     * @mbggenerated
     */
    public void setTeacherNativePlace(String teacherNativePlace) {
        this.teacherNativePlace = teacherNativePlace == null ? null : teacherNativePlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_info.teacher_marital_status
     *
     * @return the value of teacher_info.teacher_marital_status
     *
     * @mbggenerated
     */
    public String getTeacherMaritalStatus() {
        return teacherMaritalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_info.teacher_marital_status
     *
     * @param teacherMaritalStatus the value for teacher_info.teacher_marital_status
     *
     * @mbggenerated
     */
    public void setTeacherMaritalStatus(String teacherMaritalStatus) {
        this.teacherMaritalStatus = teacherMaritalStatus == null ? null : teacherMaritalStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_info.teacher_join_time
     *
     * @return the value of teacher_info.teacher_join_time
     *
     * @mbggenerated
     */
    public Date getTeacherJoinTime() {
        return teacherJoinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_info.teacher_join_time
     *
     * @param teacherJoinTime the value for teacher_info.teacher_join_time
     *
     * @mbggenerated
     */
    public void setTeacherJoinTime(Date teacherJoinTime) {
        this.teacherJoinTime = teacherJoinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_info.teacher_education
     *
     * @return the value of teacher_info.teacher_education
     *
     * @mbggenerated
     */
    public String getTeacherEducation() {
        return teacherEducation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_info.teacher_education
     *
     * @param teacherEducation the value for teacher_info.teacher_education
     *
     * @mbggenerated
     */
    public void setTeacherEducation(String teacherEducation) {
        this.teacherEducation = teacherEducation == null ? null : teacherEducation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_info.teacher_graduated_place
     *
     * @return the value of teacher_info.teacher_graduated_place
     *
     * @mbggenerated
     */
    public String getTeacherGraduatedPlace() {
        return teacherGraduatedPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_info.teacher_graduated_place
     *
     * @param teacherGraduatedPlace the value for teacher_info.teacher_graduated_place
     *
     * @mbggenerated
     */
    public void setTeacherGraduatedPlace(String teacherGraduatedPlace) {
        this.teacherGraduatedPlace = teacherGraduatedPlace == null ? null : teacherGraduatedPlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_info.teacher_phone
     *
     * @return the value of teacher_info.teacher_phone
     *
     * @mbggenerated
     */
    public String getTeacherPhone() {
        return teacherPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_info.teacher_phone
     *
     * @param teacherPhone the value for teacher_info.teacher_phone
     *
     * @mbggenerated
     */
    public void setTeacherPhone(String teacherPhone) {
        this.teacherPhone = teacherPhone == null ? null : teacherPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_info.teacher_cellphone
     *
     * @return the value of teacher_info.teacher_cellphone
     *
     * @mbggenerated
     */
    public String getTeacherCellphone() {
        return teacherCellphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_info.teacher_cellphone
     *
     * @param teacherCellphone the value for teacher_info.teacher_cellphone
     *
     * @mbggenerated
     */
    public void setTeacherCellphone(String teacherCellphone) {
        this.teacherCellphone = teacherCellphone == null ? null : teacherCellphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_info.teacher_eamil
     *
     * @return the value of teacher_info.teacher_eamil
     *
     * @mbggenerated
     */
    public String getTeacherEamil() {
        return teacherEamil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_info.teacher_eamil
     *
     * @param teacherEamil the value for teacher_info.teacher_eamil
     *
     * @mbggenerated
     */
    public void setTeacherEamil(String teacherEamil) {
        this.teacherEamil = teacherEamil == null ? null : teacherEamil.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_info.teacher_position
     *
     * @return the value of teacher_info.teacher_position
     *
     * @mbggenerated
     */
    public String getTeacherPosition() {
        return teacherPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_info.teacher_position
     *
     * @param teacherPosition the value for teacher_info.teacher_position
     *
     * @mbggenerated
     */
    public void setTeacherPosition(String teacherPosition) {
        this.teacherPosition = teacherPosition == null ? null : teacherPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_info.teacher_remark
     *
     * @return the value of teacher_info.teacher_remark
     *
     * @mbggenerated
     */
    public String getTeacherRemark() {
        return teacherRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_info.teacher_remark
     *
     * @param teacherRemark the value for teacher_info.teacher_remark
     *
     * @mbggenerated
     */
    public void setTeacherRemark(String teacherRemark) {
        this.teacherRemark = teacherRemark == null ? null : teacherRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_info.teacher_photo
     *
     * @return the value of teacher_info.teacher_photo
     *
     * @mbggenerated
     */
    public String getTeacherPhoto() {
        return teacherPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_info.teacher_photo
     *
     * @param teacherPhoto the value for teacher_info.teacher_photo
     *
     * @mbggenerated
     */
    public void setTeacherPhoto(String teacherPhoto) {
        this.teacherPhoto = teacherPhoto == null ? null : teacherPhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", teacherId=").append(teacherId);
        sb.append(", teacherName=").append(teacherName);
        sb.append(", teacherGender=").append(teacherGender);
        sb.append(", teacherBirthday=").append(teacherBirthday);
        sb.append(", teacherRacial=").append(teacherRacial);
        sb.append(", teacherNativePlace=").append(teacherNativePlace);
        sb.append(", teacherMaritalStatus=").append(teacherMaritalStatus);
        sb.append(", teacherJoinTime=").append(teacherJoinTime);
        sb.append(", teacherEducation=").append(teacherEducation);
        sb.append(", teacherGraduatedPlace=").append(teacherGraduatedPlace);
        sb.append(", teacherPhone=").append(teacherPhone);
        sb.append(", teacherCellphone=").append(teacherCellphone);
        sb.append(", teacherEamil=").append(teacherEamil);
        sb.append(", teacherPosition=").append(teacherPosition);
        sb.append(", teacherRemark=").append(teacherRemark);
        sb.append(", teacherPhoto=").append(teacherPhoto);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}