package com.education.system.entity;

import java.io.Serializable;

public class TeacherAccount implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_account.teacher_id
     *
     * @mbggenerated
     */
    private Integer teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_account.teacher_password
     *
     * @mbggenerated
     */
    private String teacherPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_account.teacher_email
     *
     * @mbggenerated
     */
    private String teacherEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_account.teacher_status
     *
     * @mbggenerated
     */
    private Integer teacherStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table teacher_account
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_account.teacher_id
     *
     * @return the value of teacher_account.teacher_id
     *
     * @mbggenerated
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_account.teacher_id
     *
     * @param teacherId the value for teacher_account.teacher_id
     *
     * @mbggenerated
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_account.teacher_password
     *
     * @return the value of teacher_account.teacher_password
     *
     * @mbggenerated
     */
    public String getTeacherPassword() {
        return teacherPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_account.teacher_password
     *
     * @param teacherPassword the value for teacher_account.teacher_password
     *
     * @mbggenerated
     */
    public void setTeacherPassword(String teacherPassword) {
        this.teacherPassword = teacherPassword == null ? null : teacherPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_account.teacher_email
     *
     * @return the value of teacher_account.teacher_email
     *
     * @mbggenerated
     */
    public String getTeacherEmail() {
        return teacherEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_account.teacher_email
     *
     * @param teacherEmail the value for teacher_account.teacher_email
     *
     * @mbggenerated
     */
    public void setTeacherEmail(String teacherEmail) {
        this.teacherEmail = teacherEmail == null ? null : teacherEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_account.teacher_status
     *
     * @return the value of teacher_account.teacher_status
     *
     * @mbggenerated
     */
    public Integer getTeacherStatus() {
        return teacherStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_account.teacher_status
     *
     * @param teacherStatus the value for teacher_account.teacher_status
     *
     * @mbggenerated
     */
    public void setTeacherStatus(Integer teacherStatus) {
        this.teacherStatus = teacherStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_account
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", teacherId=").append(teacherId);
        sb.append(", teacherPassword=").append(teacherPassword);
        sb.append(", teacherEmail=").append(teacherEmail);
        sb.append(", teacherStatus=").append(teacherStatus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}